# Exploring DuckDB & SQLMesh

Exploring FHIR data infrastructure with DuckDB and SQLMesh

| Date | User | Change Type | Remarks |  
| ---- | ---- | ----------- | ------- |
| 02/03/2026 (SGT)   | Martin | Create   | Notebook created. DuckDB exploration | 
| 17/03/2026 (SGT)   | Martin | Update   | Exploration of post-pipeline tables | 
| 23/03/2026 (SGT)   | Martin | Update   | Flattening data from other tables into silver |

# Content

* [DuckDB](#duckdb)

# DuckDB

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import duckdb
import os
from dotenv import load_dotenv

load_dotenv()

False

## Merging files

For systems that cannot handle docker files, use this to create a single merged DB

In [2]:
base_path = "../data/warehouse"
source_files = os.listdir(base_path)
source_files = [f"{base_path}/{file}" for file in source_files]
print(source_files)
target_db_path = "../data/merged_database.duckdb"

con = duckdb.connect(target_db_path)
con.execute("CREATE SCHEMA IF NOT EXISTS bronze;")

for i, file_path in enumerate(source_files):
  con.execute(f"ATTACH '{file_path}' AS source{i}")

  tables = con.execute(f"SELECT table_name FROM information_schema.tables WHERE table_catalog = 'source{i}'").fetchall()
  print(tables)
  for table_row in tables:
    table_name = table_row[0]
    table_name = f"bronze.{table_name}"

    con.execute(f"CREATE TABLE IF NOT EXISTS {table_name} AS SELECT * FROM source{i}.{table_name} LIMIT 0")
    con.execute(f"INSERT INTO {table_name} SELECT * FROM source{i}.{table_name}")

for i, file_path in enumerate(source_files):
  con.execute(f"DETACH source{i}")

con.close()

print(f"Data from {source_files} has been merged into {target_db_path}")

['../data/warehouse/mimic_fhir.duckdb', '../data/warehouse/mimic_fhir_condition.duckdb', '../data/warehouse/mimic_fhir_disp_org_obs.duckdb', '../data/warehouse/mimic_fhir_encountered.duckdb', '../data/warehouse/mimic_fhir_location.duckdb', '../data/warehouse/mimic_fhir_obs.duckdb', '../data/warehouse/mimic_fhir_patient.duckdb']
[('fhir_resources',)]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[('fhir_resources',)]
[('fhir_resources',)]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[('fhir_resources',)]
[('fhir_resources',)]
[('fhir_resources',)]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[('fhir_resources',)]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Data from ['../data/warehouse/mimic_fhir.duckdb', '../data/warehouse/mimic_fhir_condition.duckdb', '../data/warehouse/mimic_fhir_disp_org_obs.duckdb', '../data/warehouse/mimic_fhir_encountered.duckdb', '../data/warehouse/mimic_fhir_location.duckdb', '../data/warehouse/mimic_fhir_obs.duckdb', '../data/warehouse/mimic_fhir_patient.duckdb'] has been merged into ../data/merged_database.duckdb

In [ ]:
con = duckdb.connect(source_files[1])
tables = con.sql("SHOW TABLES FROM bronze").df()
print(tables)
con.close()

# Exploring Tables

Bronze tables:

- `bronze.fhir_resources`: Collection of raw FHIR resource data
- `bronze.synthea`: Synthea generated data

Silver tables:

- `silver.obs_vital`: Patient vitals recorded in long format

Intermediate tables:

- `intermediate.vitals_wide`: Flattened vitals table containing patient recorded vitals (e.g heart rate, temperature, ...)

Gold (marts) tables:

- `marts.vitals_eda`:

In [78]:
con = duckdb.connect("../data/warehouse/mimic_fhir.duckdb")
dbs = con.sql("SELECT * FROM duckdb_databases").df()
dbs

,database_name,database_oid,path,comment,tags,internal,type,readonly,encrypted,cipher
0,mimic_fhir,727,/Users/martz/Repos/MIMIC-FHIR/notebooks/../dat...,None,{'storage_version': 'v1.0.0+'},False,duckdb,False,False,None

In [79]:
tables = con.sql("SHOW ALL TABLES").df()
tables

,database,schema,name,column_names,column_types,temporary
0,mimic_fhir,bronze,fhir_resources,"[resource_type, resource_id, resource, source_...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR]",False
1,mimic_fhir,bronze,synthea,"[full_url, resource_type, resource, request, s...","[VARCHAR, VARCHAR, JSON, JSON, VARCHAR, VARCHAR]",False
2,mimic_fhir,intermediate,vitals_wide,"[encounter_id, patient_id, effective_datetime,...","[VARCHAR, VARCHAR, TIMESTAMP, DOUBLE, DOUBLE, ...",False
3,mimic_fhir,marts,vitals_eda,"[encounter_id, patient_id, effective_datetime,...","[VARCHAR, VARCHAR, TIMESTAMP, DOUBLE, DOUBLE, ...",False
4,mimic_fhir,silver,condition,"[resource_id, icd_code, icd_name, patient_id, ...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
5,mimic_fhir,silver,encounter,"[resource_id, class_code, class_name, start_ti...","[VARCHAR, VARCHAR, VARCHAR, TIMESTAMP, TIMESTA...",False
6,mimic_fhir,silver,location,"[resource_id, name, is_active, loaction_physic...","[VARCHAR, VARCHAR, INTEGER, VARCHAR, VARCHAR]",False
7,mimic_fhir,silver,medication_dispense,"[resource_id, status, encounter_id, patient_id...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
8,mimic_fhir,silver,obs_vitals,"[resource_id, patient_id, encounter_id, effect...","[VARCHAR, VARCHAR, VARCHAR, TIMESTAMP, VARCHAR...",False
9,mimic_fhir,silver,organization,"[resource_id, name, is_active, npi_value]","[VARCHAR, VARCHAR, VARCHAR, INTEGER]",False
10,mimic_fhir,silver,patient,"[resource_id, name, gender, birth_date, race, ...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
11,mimic_fhir,silver,procedure,"[resource_id, snomed_ct_id, snomed_ct_procedur...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
12,mimic_fhir,sqlmesh,_auto_restatements,"[snapshot_name, snapshot_version, next_auto_re...","[VARCHAR, VARCHAR, BIGINT]",False
13,mimic_fhir,sqlmesh,_environment_statements,"[environment_name, plan_id, environment_statem...","[VARCHAR, VARCHAR, VARCHAR]",False
14,mimic_fhir,sqlmesh,_environments,"[name, snapshots, start_at, end_at, plan_id, p...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
15,mimic_fhir,sqlmesh,_intervals,"[id, created_ts, name, identifier, version, st...","[VARCHAR, BIGINT, VARCHAR, VARCHAR, VARCHAR, B...",False
16,mimic_fhir,sqlmesh,_snapshots,"[name, identifier, version, snapshot, kind_nam...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
17,mimic_fhir,sqlmesh,_versions,"[schema_version, sqlglot_version, sqlmesh_vers...","[INTEGER, VARCHAR, VARCHAR]",False
18,mimic_fhir,sqlmesh__intermediate,intermediate__vitals_wide__53304136,"[encounter_id, patient_id, effective_datetime,...","[VARCHAR, VARCHAR, TIMESTAMP, DOUBLE, DOUBLE, ...",False
19,mimic_fhir,sqlmesh__marts,marts__vitals_eda__3335598278,"[encounter_id, patient_id, effective_datetime,...","[VARCHAR, VARCHAR, TIMESTAMP, DOUBLE, DOUBLE, ...",False

In [9]:
con.sql("SELECT * FROM bronze.synthea LIMIT 10")

┌───────────────────────────────────────────────┬──────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────┬────────────────────┬──────────────────────────────────────┐
│                   full_url                    │    resource_type     │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        resource                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         │                    request                     │    source_file     │               file_id                │

## Exploring Bronze tables

Looking to see if other sqlmesh pipelines can be created from the data

In [7]:
con.sql("SELECT * FROM bronze.fhir_resources LIMIT 10;")

┌───────────────┬──────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┐
│ resource_type │             resource_id              │                                                                                                                                                                                                                                                                            resource                                                                                                                                                                                                                                                                            │    source_file     │
│    varchar    │               varchar                │                                                                                                                                                                                                                                                                            varchar                                                                                                                                                                                                                                                                             │      varchar       │
├───────────────┼──────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ Procedure     │ ef1cc99a-f637-5480-b646-0526caa35b16 │ {"id": "ef1cc99a-f637-5480-b646-0526caa35b16", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9"}, "resourceType": "Procedure", "performedDateTime": "2169-10-24T15:42:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 2c9e78fd-57c1-5665-98e2-a90e11cd12bd │ {"id": "2c9e78fd-57c1-5665-98e2-a90e11cd12bd", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9"}, "resourceType": "Procedure", "performedDateTime": "2169-10-24T09:59:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 4fe0eae4-4ce2-5251-83d0-d11475806507 │ {"id": "4fe0eae4-4ce2-5251-83d0-d11475806507", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/ab67e413-be5f-5c55-97d2-615c1941d950"}, "resourceType": "Procedure", "performedDateTime": "2169-09-06T22:55:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 54432192-06f6-5ac4-b329-5e0c1ec2ddcf │ {"id": "54432192-06f6-5ac4-b329-5e0c1ec2ddcf", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/ab67e413-be5f-5c55-97d2-615c1941d950"}, "resourceType": "Procedure", "performedDateTime": "2169-09-06T17:35:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 91218afd-ab8b-5ed9-88c8-fadb6cffb90e │ {"id": "91218afd-ab8b-5ed9-88c8-fadb6cffb90e", "code": {"coding": [{"code": "386478007", "system": "http://snomed.info/sct", "display": "Triage: emergency center (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9"}, "resourceType": "Procedure", "performedDateTime": "2169-10-24T09:57:00-04:00"}              │ ProcedureED.ndjson │
│ Procedure     │ 34f170a9-d41b-5176-8b71-39a7aa353815 │ {"id": "34f170a9-d41b-5176-8b71-39a7aa353815", "code": {"coding": [{"code": "386478007", "system": "http://snomed.info/sct", "display": "Triage: emergency center (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/ab67e413-be5f-5c55-97d2-615c1941d950"}, "resourceType": "Procedure", "performedDateTime": "2169-09-06T17:34:00-04:00"}              │ ProcedureED.ndjson │
│ Procedure     │ 69c338ec-d271-5b60-acdb-4014a661cd3f │ {"id": "69c338ec-d271-5b60-acdb-4014a661cd3f", "code": {"coding": [{"code": "386478007", "system": "http://snomed.info/sct", "display": "Triage: emergency center (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe"}, "resourceType": "Procedure", "performedDateTime": "2165-10-01T15:51:00-04:00"}              │ ProcedureED.ndjson │
│ Procedure     │ c54a56d7-0a95-5395-a9d1-a1d915ef7784 │ {"id": "c54a56d7-0a95-5395-a9d1-a1d915ef7784", "code": {"coding": [{"code": "386478007", "system": "http://snomed.info/sct", "display": "Triage: emergency center (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/8178aca7-ebbc-53db-a425-4f9a5c25786b"}, "resourceType": "Procedure", "performedDateTime": "2169-10-08T18:39:00-04:00"}              │ ProcedureED.ndjson │
│ Procedure     │ 21527095-eb3a-590d-8a51-9f915c7c95b6 │ {"id": "21527095-eb3a-590d-8a51-9f915c7c95b6", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/8178aca7-ebbc-53db-a425-4f9a5c25786b"}, "resourceType": "Procedure", "performedDateTime": "2169-10-08T20:57:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 11333007-4b3a-5092-8fc2-b39888bdc2aa │ {"id": "11333007-4b3a-5092-8fc2-b39888bdc2aa", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/8178aca7-ebbc-53db-a425-4f9a5c25786b"}, "resourceType": "Procedure", "performedDateTime": "2169-10-08T18:41:00-04:00"} │ ProcedureED.ndjson │
├───────────────┴──────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          4 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [8]:
con.sql("SELECT DISTINCT resource_type FROM bronze.fhir_resources;")

┌────────────────────┐
│   resource_type    │
│      varchar       │
├────────────────────┤
│ Organization       │
│ Location           │
│ Observation        │
│ Procedure          │
│ Condition          │
│ MedicationDispense │
│ Encounter          │
│ Patient            │
└────────────────────┘

### 1. Organization

[Source](https://build.fhir.org/organization.html)

Contains a single organisation: "Beth Israel Deaconess Medical Center"

In [80]:
# Silver table flatten query
con.sql("""
  SELECT 
    resource->>'id' AS resource_id,
    resource->>'name' AS name,
    resource->>'active' AS is_active,
    TRY_CAST(resource->'identifier'->0->>'value' AS INT32) AS npi_value
  FROM bronze.fhir_resources
  WHERE resource_type='Organization';
""")

┌──────────────────────────────────────┬──────────────────────────────────────┬───────────┬────────────┐
│             resource_id              │                 name                 │ is_active │ npi_value  │
│               varchar                │               varchar                │  varchar  │   int32    │
├──────────────────────────────────────┼──────────────────────────────────────┼───────────┼────────────┤
│ ee172322-118b-5716-abbc-18e4c5437e15 │ Beth Israel Deaconess Medical Center │ true      │ 1194052720 │
└──────────────────────────────────────┴──────────────────────────────────────┴───────────┴────────────┘

In [81]:
# Silver table test query
con.sql("SELECT * FROM silver.organization")

┌──────────────────────────────────────┬──────────────────────────────────────┬───────────┬────────────┐
│             resource_id              │                 name                 │ is_active │ npi_value  │
│               varchar                │               varchar                │  varchar  │   int32    │
├──────────────────────────────────────┼──────────────────────────────────────┼───────────┼────────────┤
│ ee172322-118b-5716-abbc-18e4c5437e15 │ Beth Israel Deaconess Medical Center │ true      │ 1194052720 │
└──────────────────────────────────────┴──────────────────────────────────────┴───────────┴────────────┘

### 2. Location

[Source](https://build.fhir.org/location.html)

39 total locations. Each is a specialist clinic in the hospital

In [ ]:
# Flatten Location resource
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->>'name' AS name,
    CASE WHEN resource->>'status' = 'active' THEN 1 ELSE 0 END AS is_active,
    resource->'physicalType'->'coding'->0->>'display' AS loaction_physical_type,
    regexp_replace(resource->'managingOrganization'->>'reference', 'Organization/', '') AS organization_id
  FROM bronze.fhir_resources
  WHERE resource_type='Location'
  LIMIT 10;
""")

┌──────────────────────────────────────┬──────────────────────────────────────────────────┬───────────┬────────────────────────┬──────────────────────────────────────┐
│             resource_id              │                       name                       │ is_active │ loaction_physical_type │           organization_id            │
│               varchar                │                     varchar                      │   int32   │        varchar         │               varchar                │
├──────────────────────────────────────┼──────────────────────────────────────────────────┼───────────┼────────────────────────┼──────────────────────────────────────┤
│ ecbf468a-22ec-5320-8e11-6ebcc918dad5 │ Cardiology Surgery Intermediate                  │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 501cd59a-cd8a-5f98-8298-2ca9c897d59f │ Emergency Department                             │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ f4ed77ed-3be3-5700-bc6a-3622ca10f90f │ Discharge Lounge                                 │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 30fa4243-10dc-5b14-8819-e4785f8dd4a7 │ Coronary Care Unit (CCU)                         │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ dcde0b27-37b5-5ef1-8d7e-85d608901e2b │ Medical/Surgical Intensive Care Unit (MICU/SICU) │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 7fc6d652-37b4-5812-9412-a1e397a11d7f │ Med/Surg/GYN                                     │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 73a95bb4-bc53-5ad9-ba8b-0cc7d99bc51f │ Unknown                                          │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ d82eeafd-5ac3-5765-8eb2-2b4153978abb │ Med/Surg/Trauma                                  │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 77b3f959-fa2c-5599-8713-a86815b29a4a │ Medical Intensive Care Unit (MICU)               │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ f35a0cd4-fadf-5ba5-9648-64ccf26866f5 │ Surgery                                          │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
├──────────────────────────────────────┴──────────────────────────────────────────────────┴───────────┴────────────────────────┴──────────────────────────────────────┤
│ 10 rows                                                                                                                                                   5 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [82]:
# Check silver.location table
con.sql("SELECT * FROM silver.location LIMIT 10;")

┌──────────────────────────────────────┬──────────────────────────────────────────────────┬───────────┬────────────────────────┬──────────────────────────────────────┐
│             resource_id              │                       name                       │ is_active │ loaction_physical_type │           organization_id            │
│               varchar                │                     varchar                      │   int32   │        varchar         │               varchar                │
├──────────────────────────────────────┼──────────────────────────────────────────────────┼───────────┼────────────────────────┼──────────────────────────────────────┤
│ ecbf468a-22ec-5320-8e11-6ebcc918dad5 │ Cardiology Surgery Intermediate                  │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 501cd59a-cd8a-5f98-8298-2ca9c897d59f │ Emergency Department                             │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ f4ed77ed-3be3-5700-bc6a-3622ca10f90f │ Discharge Lounge                                 │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 30fa4243-10dc-5b14-8819-e4785f8dd4a7 │ Coronary Care Unit (CCU)                         │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ dcde0b27-37b5-5ef1-8d7e-85d608901e2b │ Medical/Surgical Intensive Care Unit (MICU/SICU) │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 7fc6d652-37b4-5812-9412-a1e397a11d7f │ Med/Surg/GYN                                     │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 73a95bb4-bc53-5ad9-ba8b-0cc7d99bc51f │ Unknown                                          │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ d82eeafd-5ac3-5765-8eb2-2b4153978abb │ Med/Surg/Trauma                                  │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 77b3f959-fa2c-5599-8713-a86815b29a4a │ Medical Intensive Care Unit (MICU)               │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ f35a0cd4-fadf-5ba5-9648-64ccf26866f5 │ Surgery                                          │         1 │ Ward                   │ ee172322-118b-5716-abbc-18e4c5437e15 │
├──────────────────────────────────────┴──────────────────────────────────────────────────┴───────────┴────────────────────────┴──────────────────────────────────────┤
│ 10 rows                                                                                                                                                   5 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

### 3. Procedure

- [Source](https://build.fhir.org/location.html)
- [Procedure Codes SNOMED_CT](https://build.fhir.org/valueset-procedure-code.html)

1,989,697 total procedure entries. Each has `patient_id` and an `encounter_id`

In [44]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->'code'->'coding'->0->>'code' AS snomed_ct_id,
    regexp_replace(resource->'code'->'coding'->0->>'display', ' \(procedure\)', '') AS snomed_ct_procedure,
    resource->>'status' AS status,
    regexp_replace(resource->'subject'->>'reference', 'Patient/', '') AS patient_id,
    regexp_replace(resource->'encounter'->>'reference', 'Encounter/', '') AS encounter_id,
    (resource->>'performedDateTime')::TIMESTAMP AS performed_datetime
  FROM bronze.fhir_resources
  WHERE resource_type='Procedure'
  LIMIT 10;
""")

┌──────────────────────────────────────┬──────────────┬───────────────────────────────────────┬───────────┬──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┐
│             resource_id              │ snomed_ct_id │          snomed_ct_procedure          │  status   │              patient_id              │             encounter_id             │ performed_datetime  │
│               varchar                │   varchar    │                varchar                │  varchar  │               varchar                │               varchar                │      timestamp      │
├──────────────────────────────────────┼──────────────┼───────────────────────────────────────┼───────────┼──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┤
│ ef1cc99a-f637-5480-b646-0526caa35b16 │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 15:42:00 │
│ 2c9e78fd-57c1-5665-98e2-a90e11cd12bd │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 09:59:00 │
│ 4fe0eae4-4ce2-5251-83d0-d11475806507 │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 22:55:00 │
│ 54432192-06f6-5ac4-b329-5e0c1ec2ddcf │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 17:35:00 │
│ 91218afd-ab8b-5ed9-88c8-fadb6cffb90e │ 386478007    │ Triage: emergency center              │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 09:57:00 │
│ 34f170a9-d41b-5176-8b71-39a7aa353815 │ 386478007    │ Triage: emergency center              │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 17:34:00 │
│ 69c338ec-d271-5b60-acdb-4014a661cd3f │ 386478007    │ Triage: emergency center              │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe │ 2165-10-01 15:51:00 │
│ c54a56d7-0a95-5395-a9d1-a1d915ef7784 │ 386478007    │ Triage: emergency center              │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ 2169-10-08 18:39:00 │
│ 21527095-eb3a-590d-8a51-9f915c7c95b6 │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ 2169-10-08 20:57:00 │
│ 11333007-4b3a-5092-8fc2-b39888bdc2aa │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ 2169-10-08 18:41:00 │
├──────────────────────────────────────┴──────────────┴───────────────────────────────────────┴───────────┴──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┤
│ 10 rows                                                                                                                                                                                           7 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [83]:
# Check silver.procedure
con.sql("SELECT * FROM silver.procedure LIMIT 10;")

┌──────────────────────────────────────┬──────────────┬───────────────────────────────────────┬───────────┬──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┐
│             resource_id              │ snomed_ct_id │          snomed_ct_procedure          │  status   │              patient_id              │             encounter_id             │ performed_datetime  │
│               varchar                │   varchar    │                varchar                │  varchar  │               varchar                │               varchar                │      timestamp      │
├──────────────────────────────────────┼──────────────┼───────────────────────────────────────┼───────────┼──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┤
│ ef1cc99a-f637-5480-b646-0526caa35b16 │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 15:42:00 │
│ 2c9e78fd-57c1-5665-98e2-a90e11cd12bd │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 09:59:00 │
│ 4fe0eae4-4ce2-5251-83d0-d11475806507 │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 22:55:00 │
│ 54432192-06f6-5ac4-b329-5e0c1ec2ddcf │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 17:35:00 │
│ 91218afd-ab8b-5ed9-88c8-fadb6cffb90e │ 386478007    │ Triage: emergency center              │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 09:57:00 │
│ 34f170a9-d41b-5176-8b71-39a7aa353815 │ 386478007    │ Triage: emergency center              │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 17:34:00 │
│ 69c338ec-d271-5b60-acdb-4014a661cd3f │ 386478007    │ Triage: emergency center              │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe │ 2165-10-01 15:51:00 │
│ c54a56d7-0a95-5395-a9d1-a1d915ef7784 │ 386478007    │ Triage: emergency center              │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ 2169-10-08 18:39:00 │
│ 21527095-eb3a-590d-8a51-9f915c7c95b6 │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ 2169-10-08 20:57:00 │
│ 11333007-4b3a-5092-8fc2-b39888bdc2aa │ 410188000    │ Taking patient vital signs assessment │ completed │ 000000ba-735e-5858-a92d-b856d73dd69a │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ 2169-10-08 18:41:00 │
├──────────────────────────────────────┴──────────────┴───────────────────────────────────────┴───────────┴──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┤
│ 10 rows                                                                                                                                                                                           7 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

### 4. Condition

[Source](https://build.fhir.org/condition.html)

899,050 entries in condition table.

Column Details:
- `condtion_code`: [ICD-10 coding](https://www.icd10data.com/)
- `condtion_category`: "problem-list-item" | "encounter-diagnosis" [Source](https://build.fhir.org/valueset-condition-category.html)

In [50]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->'code'->'coding'->0->>'code' AS icd_code,
    resource->'code'->'coding'->0->>'display' AS icd_name,
    regexp_replace(resource->'subject'->>'reference', 'Patient/', '') AS patient_id,
    resource->'category'->0->'coding'->0->>'code' AS condition_category,
    regexp_replace(resource->'encounter'->>'reference', 'Encounter/', '') AS encounter_id
  FROM bronze.fhir_resources
  WHERE resource_type='Condition'
  LIMIT 10;
""")

┌──────────────────────────────────────┬──────────┬─────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬──────────────────────────────────────┐
│             resource_id              │ icd_code │                                icd_name                                 │              patient_id              │ condition_category  │             encounter_id             │
│               varchar                │ varchar  │                                 varchar                                 │               varchar                │       varchar       │               varchar                │
├──────────────────────────────────────┼──────────┼─────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼──────────────────────────────────────┤
│ 3ec3187d-b760-531a-a02d-a69b58b66fe1 │ T402X5A  │ Adverse effect of other opioids, initial encounter                      │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │
│ 95ff6e76-810b-50df-9c56-f6ef903718ac │ M25561   │ Pain in right knee                                                      │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ ab67e413-be5f-5c55-97d2-615c1941d950 │
│ 63dd1073-6a9d-5998-82be-4937289f9b0c │ 7242     │ Lumbago                                                                 │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe │
│ dbbee4e7-a000-55b0-9d77-dd940c918613 │ Y9289    │ Other specified places as the place of occurrence of the external cause │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │
│ a845f5ba-7980-5991-a5e1-c8c839254d0d │ E7800    │ Pure hypercholesterolemia, unspecified                                  │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │
│ 63880b75-606e-597b-b8e6-a09239afb9b5 │ M7989    │ Other specified soft tissue disorders                                   │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │
│ 4ef4871a-7320-5998-a107-fb6e052b9d9e │ M25561   │ Pain in right knee                                                      │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │
│ 7410d7df-7e2e-55d1-98bc-4402e860def5 │ M25561   │ Pain in right knee                                                      │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │
│ b24feb5d-b06d-5641-95bb-23aa593a959a │ I10      │ Essential (primary) hypertension                                        │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │
│ 8b3d5aa6-c882-50a9-be9c-d6dacab4c288 │ 4019     │ Unspecified essential hypertension                                      │ 000000ba-735e-5858-a92d-b856d73dd69a │ encounter-diagnosis │ 3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe │
├──────────────────────────────────────┴──────────┴─────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴──────────────────────────────────────┤
│ 10 rows                                                                                                                                                                                                             6 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [84]:
# Test silver.condition
con.sql("SELECT * FROM silver.condition LIMIT 10;")

┌──────────────────────────────────────┬──────────┬─────────────────────────────────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬──────────────────────────────────────┐
│             resource_id              │ icd_code │                            icd_name                             │              patient_id              │ condition_category  │             encounter_id             │
│               varchar                │ varchar  │                             varchar                             │               varchar                │       varchar       │               varchar                │
├──────────────────────────────────────┼──────────┼─────────────────────────────────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼──────────────────────────────────────┤
│ c9647885-10fa-5b71-83ce-e8f471ffadf3 │ R079     │ Chest pain, unspecified                                         │ 23062449-664f-58cc-813e-2eb4019fe9ec │ encounter-diagnosis │ 34c7f1a0-29cc-54cb-808e-8353baaa46bf │
│ 95bd0688-c13e-53bb-b72e-bdb4a4cbf6c1 │ 78650    │ Chest pain, unspecified                                         │ 23062449-664f-58cc-813e-2eb4019fe9ec │ encounter-diagnosis │ fb1195f1-18fb-56a0-8f36-231f6bb3dbe4 │
│ dda75093-aef1-5679-960b-d625f1f83cf8 │ D333     │ Benign neoplasm of cranial nerves                               │ 23062449-664f-58cc-813e-2eb4019fe9ec │ encounter-diagnosis │ 34c7f1a0-29cc-54cb-808e-8353baaa46bf │
│ 500a36ca-0747-5850-bc2d-9852261610e5 │ 78701    │ Nausea with vomiting                                            │ 230633bd-3fdd-514c-81a8-f6ad48caf808 │ encounter-diagnosis │ 52f2b397-f0e0-527c-9302-36e465f362b8 │
│ ba6ee856-0ca4-5f7a-aca9-f48a37b84c7a │ 5589     │ Other and unspecified noninfectious gastroenteritis and colitis │ 23063a25-5656-5222-a2b2-fad34248639b │ encounter-diagnosis │ 39375037-9c0a-5d8f-a870-5ae2b7ad1bb8 │
│ d053e6ab-9ae1-5bf2-aa38-3c79579facaf │ I10      │ Essential (primary) hypertension                                │ 23063a25-5656-5222-a2b2-fad34248639b │ encounter-diagnosis │ eeb32bdb-5b28-5d77-944c-bd23c3a483bc │
│ 17f4e51a-99ed-55ca-998f-7c7e7a0f9dc5 │ 4019     │ Unspecified essential hypertension                              │ 23063a25-5656-5222-a2b2-fad34248639b │ encounter-diagnosis │ 6326ff84-e820-5cd3-9a81-57cc180c7fd1 │
│ 09e6b0ef-c575-5004-824b-487d7c0ae70c │ 78791    │ Diarrhea                                                        │ 23063a25-5656-5222-a2b2-fad34248639b │ encounter-diagnosis │ 76f303f7-4720-5cdf-a5a9-d2d3da2dce34 │
│ 88423816-bf0f-5bb6-ba8b-bfb834543857 │ 78701    │ Nausea with vomiting                                            │ 23063a25-5656-5222-a2b2-fad34248639b │ encounter-diagnosis │ 76f303f7-4720-5cdf-a5a9-d2d3da2dce34 │
│ 47f126f7-b3ce-5144-9d15-d2437c2c7d1a │ 73300    │ Osteoporosis, unspecified                                       │ 23063a25-5656-5222-a2b2-fad34248639b │ encounter-diagnosis │ 2f19c5af-b146-5ef1-b27f-8685235bd769 │
├──────────────────────────────────────┴──────────┴─────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴──────────────────────────────────────┤
│ 10 rows                                                                                                                                                                                                     6 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

### 5. Medication Dispense

[Source](https://build.fhir.org/medicationdispense.html)

1,586,053 entries in bronze

In [60]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->>'status' AS status,
    regexp_replace(resource->'context'->>'reference', 'Encounter/', '') AS encounter_id,
    regexp_replace(resource->'subject'->>'reference', 'Patient/', '') AS patient_id,
    resource->'medicationCodeableConcept'->'coding'->0->>'code' AS medication_code,
    resource->'medicationCodeableConcept'->>'text' AS medication_name,
    (resource->>'whenHandedOver')::TIMESTAMP AS handed_over_timestamp
  FROM bronze.fhir_resources
  WHERE resource_type='MedicationDispense'
  LIMIT 10;
""")

┌──────────────────────────────────────┬─────────┬──────────────────────────────────────┬──────────────────────────────────────┬─────────────────┬──────────────────────────────┬───────────────────────┐
│             resource_id              │ status  │             encounter_id             │              patient_id              │ medication_code │       medication_name        │ handed_over_timestamp │
│               varchar                │ varchar │               varchar                │               varchar                │     varchar     │           varchar            │       timestamp       │
├──────────────────────────────────────┼─────────┼──────────────────────────────────────┼──────────────────────────────────────┼─────────────────┼──────────────────────────────┼───────────────────────┤
│ a98720b0-042b-5084-8d3a-2f326e89f08a │ unknown │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 078733          │ LORazepam 2mg/1mL 1mL SYR    │ 2169-10-24 21:47:00   │
│ 237d8619-53ba-5046-a30d-e4533c5b5bb6 │ unknown │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 003755          │ LORazepam 2mg/1mL 1mL SYR    │ 2169-10-24 21:47:00   │
│ b52fb87c-3e16-5a79-ab7d-c883c3b07fdf │ unknown │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 003753          │ LORazepam 2mg/1mL 1mL SYR    │ 2169-10-24 21:47:00   │
│ 0e68093f-a619-5ef2-b1c9-09efa984382f │ unknown │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 061716          │ Ondansetron 4mg/2mL 2mL VIAL │ 2169-10-24 19:43:00   │
│ d0c1ced1-6fcb-512b-a66e-cf321d1bf322 │ unknown │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 015869          │ Ondansetron 4mg/2mL 2mL VIAL │ 2169-10-24 19:43:00   │
│ f5e8239a-bf14-53dc-9d5c-4df25d982ac3 │ unknown │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 041562          │ Ondansetron ODT 4mg TAB      │ 2169-10-24 16:19:00   │
│ 05fd2b0e-9b57-5a4d-8168-f8b1069865ec │ unknown │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 008348          │ Ibuprofen 400mg TAB          │ 2169-10-24 11:03:00   │
│ ac7e48ea-74a0-5852-988a-eb0d929871e8 │ unknown │ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ 000000ba-735e-5858-a92d-b856d73dd69a │ 004490          │ Acetaminophen 500mg TAB      │ 2169-10-08 20:03:00   │
│ 444301f4-871f-5c0f-9e0f-9eea64011cd7 │ unknown │ 3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe │ 000000ba-735e-5858-a92d-b856d73dd69a │ 004204          │ Hydrocodone-Acetaminophen    │ 2165-10-01 21:06:00   │
│ ec695824-206b-536e-85eb-cc579b12b0ba │ unknown │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 016926          │ AmLODIPine 5mg TAB           │ 2169-10-24 15:28:00   │
├──────────────────────────────────────┴─────────┴──────────────────────────────────────┴──────────────────────────────────────┴─────────────────┴──────────────────────────────┴───────────────────────┤
│ 10 rows                                                                                                                                                                                     7 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [85]:
# Test silver.medication_dispense
con.sql("SELECT * FROM silver.medication_dispense LIMIT 10;")

┌──────────────────────────────────────┬─────────┬──────────────────────────────────────┬──────────────────────────────────────┬─────────────────┬─────────────────────────────┬───────────────────────┐
│             resource_id              │ status  │             encounter_id             │              patient_id              │ medication_code │       medication_name       │ handed_over_timestamp │
│               varchar                │ varchar │               varchar                │               varchar                │     varchar     │           varchar           │       timestamp       │
├──────────────────────────────────────┼─────────┼──────────────────────────────────────┼──────────────────────────────────────┼─────────────────┼─────────────────────────────┼───────────────────────┤
│ 9f3fcc49-d9f1-5efc-9ba2-2c620bfce473 │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 038861          │ Lidocaine Jelly 2% (Urojet) │ 2171-02-10 11:40:00   │
│ 492af956-19a4-52af-9a58-81d597bd3c96 │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 065758          │ Acetaminophen (Liquid)      │ 2171-02-10 09:25:00   │
│ c1c333bf-90de-506a-a75a-cfa2e0079168 │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 046770          │ Levofloxacin                │ 2171-02-10 09:43:00   │
│ a53bde1b-6d54-53dd-a505-57f793ee0bde │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 015869          │ Ondansetron                 │ 2171-02-10 09:53:00   │
│ 1585c987-10fe-5974-8ad2-24b5ec855537 │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 004481          │ Acetaminophen (Liquid)      │ 2171-02-10 09:25:00   │
│ a65a644f-e086-55e4-9c5f-c95ac9d9dfa8 │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 023196          │ Acetaminophen (Liquid)      │ 2171-02-10 09:25:00   │
│ c9f81fba-58a3-5362-b6a7-200593b4157a │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 061716          │ Ondansetron                 │ 2171-02-10 09:53:00   │
│ 4c3ae150-27af-56ed-a1e1-1b3d9e675eae │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 003780          │ Midazolam                   │ 2171-02-10 10:02:00   │
│ 3ce3d1aa-5790-57bf-8c02-fb92e9b153ee │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 051279          │ Midazolam                   │ 2171-02-10 10:02:00   │
│ c8f898a5-8a62-5368-848d-5e9d6b8d529f │ unknown │ e2bf0c31-f54c-5280-9174-c76554cb2ab8 │ 13dc4151-7e7c-5c32-9a60-cf2683d3a668 │ 041385          │ Fentanyl                    │ 2171-02-10 10:03:00   │
├──────────────────────────────────────┴─────────┴──────────────────────────────────────┴──────────────────────────────────────┴─────────────────┴─────────────────────────────┴───────────────────────┤
│ 10 rows                                                                                                                                                                                    7 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## 6. Encounter

[Source](https://build.fhir.org/encounter.html)

425,087 entries in encounter

In [70]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->'class'->>'code' AS class_code,
    resource->'class'->>'display' AS class_name,
    (resource->'period'->>'start')::TIMESTAMP AS start_timestamp,
    (resource->'period'->>'end')::TIMESTAMP AS end_timestamp,
    resource->>'status' AS status,
    regexp_replace(resource->'subject'->>'reference', 'Patient/', '') AS patient_id,
    resource->'hospitalization'->'admitSource'->'coding'->0->>'code' AS admit_source,
    resource->'hospitalization'->'dischargeDisposition'->'coding'->0->>'code' AS discharge_disposition,
    regexp_replace(resource->'serviceProvider'->>'reference', 'Organization/', '') AS organization_id
  FROM bronze.fhir_resources
  WHERE resource_type='Encounter'
  LIMIT 10;
""")

┌──────────────────────────────────────┬────────────┬────────────┬─────────────────────┬─────────────────────┬──────────┬──────────────────────────────────────┬──────────────┬───────────────────────┬──────────────────────────────────────┐
│             resource_id              │ class_code │ class_name │   start_timestamp   │    end_timestamp    │  status  │              patient_id              │ admit_source │ discharge_disposition │           organization_id            │
│               varchar                │  varchar   │  varchar   │      timestamp      │      timestamp      │ varchar  │               varchar                │   varchar    │        varchar        │               varchar                │
├──────────────────────────────────────┼────────────┼────────────┼─────────────────────┼─────────────────────┼──────────┼──────────────────────────────────────┼──────────────┼───────────────────────┼──────────────────────────────────────┤
│ ab67e413-be5f-5c55-97d2-615c1941d950 │ EMER       │ emergency  │ 2169-09-06 17:34:00 │ 2169-09-06 23:32:00 │ finished │ 000000ba-735e-5858-a92d-b856d73dd69a │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ EMER       │ emergency  │ 2169-10-24 09:57:00 │ 2169-10-25 08:46:00 │ finished │ 000000ba-735e-5858-a92d-b856d73dd69a │ AMBULANCE    │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ EMER       │ emergency  │ 2169-10-08 18:39:00 │ 2169-10-08 21:21:00 │ finished │ 000000ba-735e-5858-a92d-b856d73dd69a │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe │ EMER       │ emergency  │ 2165-10-01 15:51:00 │ 2165-10-01 21:21:00 │ finished │ 000000ba-735e-5858-a92d-b856d73dd69a │ AMBULANCE    │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ e2c6b3c7-9d0d-59ae-adc7-6f611735dd40 │ EMER       │ emergency  │ 2142-06-12 05:50:00 │ 2142-06-12 13:52:00 │ finished │ 0000374c-6367-524e-92f8-eb3ce9074f0a │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 75fe8174-3f20-5c83-841e-7a4d0715c80f │ EMER       │ emergency  │ 2135-12-15 12:50:00 │ 2135-12-15 18:31:32 │ finished │ 000048d5-5ac9-57bc-9316-3c582c37b884 │ WALK IN      │ ADMITTED              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ cb9937e8-57f6-5b12-8c00-561a6e155686 │ EMER       │ emergency  │ 2140-03-08 21:08:00 │ 2140-03-08 23:16:00 │ finished │ 000048d5-5ac9-57bc-9316-3c582c37b884 │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ c2c18e9c-1177-5b71-aa93-e1eae57868b5 │ EMER       │ emergency  │ 2141-08-24 10:52:00 │ 2141-08-24 13:34:00 │ finished │ 0000ad47-7103-5f54-970d-dafc42fd12f9 │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 7934255b-2d65-52a5-a6ae-4842f955b51a │ EMER       │ emergency  │ 2142-10-17 14:51:00 │ 2142-10-18 00:01:00 │ finished │ 0000ad47-7103-5f54-970d-dafc42fd12f9 │ WALK IN      │ ADMITTED              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 9c224d41-940f-5f2a-9b13-54029feacf37 │ EMER       │ emergency  │ 2147-08-09 18:30:00 │ 2147-08-09 21:08:00 │ finished │ 0000ad47-7103-5f54-970d-dafc42fd12f9 │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
├──────────────────────────────────────┴────────────┴────────────┴─────────────────────┴─────────────────────┴──────────┴──────────────────────────────────────┴──────────────┴───────────────────────┴──────────────────────────────────────┤
│ 10 rows                                                                                                                                                                                                                         10 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [86]:
# Text silver.encounter
con.sql("SELECT * FROM silver.encounter LIMIT 10;")

┌──────────────────────────────────────┬────────────┬────────────┬─────────────────────┬─────────────────────┬──────────┬──────────────────────────────────────┬──────────────┬───────────────────────┬──────────────────────────────────────┐
│             resource_id              │ class_code │ class_name │   start_timestamp   │    end_timestamp    │  status  │              patient_id              │ admit_source │ discharge_disposition │           organization_id            │
│               varchar                │  varchar   │  varchar   │      timestamp      │      timestamp      │ varchar  │               varchar                │   varchar    │        varchar        │               varchar                │
├──────────────────────────────────────┼────────────┼────────────┼─────────────────────┼─────────────────────┼──────────┼──────────────────────────────────────┼──────────────┼───────────────────────┼──────────────────────────────────────┤
│ ab67e413-be5f-5c55-97d2-615c1941d950 │ EMER       │ emergency  │ 2169-09-06 17:34:00 │ 2169-09-06 23:32:00 │ finished │ 000000ba-735e-5858-a92d-b856d73dd69a │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ EMER       │ emergency  │ 2169-10-24 09:57:00 │ 2169-10-25 08:46:00 │ finished │ 000000ba-735e-5858-a92d-b856d73dd69a │ AMBULANCE    │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 8178aca7-ebbc-53db-a425-4f9a5c25786b │ EMER       │ emergency  │ 2169-10-08 18:39:00 │ 2169-10-08 21:21:00 │ finished │ 000000ba-735e-5858-a92d-b856d73dd69a │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe │ EMER       │ emergency  │ 2165-10-01 15:51:00 │ 2165-10-01 21:21:00 │ finished │ 000000ba-735e-5858-a92d-b856d73dd69a │ AMBULANCE    │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ e2c6b3c7-9d0d-59ae-adc7-6f611735dd40 │ EMER       │ emergency  │ 2142-06-12 05:50:00 │ 2142-06-12 13:52:00 │ finished │ 0000374c-6367-524e-92f8-eb3ce9074f0a │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 75fe8174-3f20-5c83-841e-7a4d0715c80f │ EMER       │ emergency  │ 2135-12-15 12:50:00 │ 2135-12-15 18:31:32 │ finished │ 000048d5-5ac9-57bc-9316-3c582c37b884 │ WALK IN      │ ADMITTED              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ cb9937e8-57f6-5b12-8c00-561a6e155686 │ EMER       │ emergency  │ 2140-03-08 21:08:00 │ 2140-03-08 23:16:00 │ finished │ 000048d5-5ac9-57bc-9316-3c582c37b884 │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ c2c18e9c-1177-5b71-aa93-e1eae57868b5 │ EMER       │ emergency  │ 2141-08-24 10:52:00 │ 2141-08-24 13:34:00 │ finished │ 0000ad47-7103-5f54-970d-dafc42fd12f9 │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 7934255b-2d65-52a5-a6ae-4842f955b51a │ EMER       │ emergency  │ 2142-10-17 14:51:00 │ 2142-10-18 00:01:00 │ finished │ 0000ad47-7103-5f54-970d-dafc42fd12f9 │ WALK IN      │ ADMITTED              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 9c224d41-940f-5f2a-9b13-54029feacf37 │ EMER       │ emergency  │ 2147-08-09 18:30:00 │ 2147-08-09 21:08:00 │ finished │ 0000ad47-7103-5f54-970d-dafc42fd12f9 │ WALK IN      │ HOME                  │ ee172322-118b-5716-abbc-18e4c5437e15 │
├──────────────────────────────────────┴────────────┴────────────┴─────────────────────┴─────────────────────┴──────────┴──────────────────────────────────────┴──────────────┴───────────────────────┴──────────────────────────────────────┤
│ 10 rows                                                                                                                                                                                                                         10 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

### 7. Patient

[Source](https://build.fhir.org/patient.html)

299,712 patients in data

In [74]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->'name'->0->>'family' AS name,
    resource->>'gender' AS gender,
    resource->>'birthDate' AS birth_date,
    resource->'extension'->0->'extension'->0->'valueCoding'->>'display' AS race,
    resource->'extension'->1->'extension'->0->'valueCoding'->>'display' AS ethnicity,
    resource->'identifier'->0->>'value' AS patient_num,
    resource->'communication'->0->'language'->'coding'->0->>'code' AS language,
    resource->'maritalStatus'->'coding'->0->>'code' AS marital_status,
    regexp_replace(resource->'managingOrganization'->>'reference', 'Organization/', '') AS organization_id
  FROM bronze.fhir_resources
  WHERE resource_type='Patient'
  LIMIT 10;
""")

┌──────────────────────────────────────┬──────────────────┬─────────┬────────────┬─────────┬────────────────────────┬─────────────┬──────────┬────────────────┬──────────────────────────────────────┐
│             resource_id              │       name       │ gender  │ birth_date │  race   │       ethnicity        │ patient_num │ language │ marital_status │           organization_id            │
│               varchar                │     varchar      │ varchar │  varchar   │ varchar │        varchar         │   varchar   │ varchar  │    varchar     │               varchar                │
├──────────────────────────────────────┼──────────────────┼─────────┼────────────┼─────────┼────────────────────────┼─────────────┼──────────┼────────────────┼──────────────────────────────────────┤
│ 0a8eebfd-a352-522e-89f0-1d4a13abdebc │ Patient_10000032 │ female  │ 2128-05-06 │ White   │ Not Hispanic or Latino │ 10000032    │ en       │ W              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 55b28161-ecdb-5c57-ba06-9f0b28e71053 │ Patient_10000084 │ male    │ 2088-11-20 │ White   │ Not Hispanic or Latino │ 10000084    │ en       │ M              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ c0ebed23-92f0-56a9-9e05-206ce34dd997 │ Patient_10000108 │ male    │ 2138-09-16 │ White   │ Not Hispanic or Latino │ 10000108    │ en       │ S              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 0bdc4fe8-eaa3-5528-ac63-e0aab2933677 │ Patient_10000115 │ male    │ 2130-12-10 │ White   │ Not Hispanic or Latino │ 10000115    │ NULL     │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 6c5795f2-6594-52a6-a183-d438112a2f58 │ Patient_10000117 │ female  │ 2126-08-14 │ White   │ Not Hispanic or Latino │ 10000117    │ en       │ D              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ dce1cd58-4658-5c31-9c03-3c7fc7d52d23 │ Patient_10000178 │ female  │ 2098-04-08 │ Asian   │ Not Hispanic or Latino │ 10000178    │ NULL     │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 2cab4d98-851c-5574-bf3a-2b273d24713e │ Patient_10000248 │ male    │ 2158-11-29 │ White   │ Not Hispanic or Latino │ 10000248    │ en       │ M              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 963c95a5-db36-58b1-a431-11cc6c073a86 │ Patient_10000285 │ male    │ 2125-11-26 │ unknown │ NULL                   │ 10000285    │ NULL     │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 136049cd-701f-5238-b988-b18f4e93a74e │ Patient_10000473 │ male    │ 2057-03-15 │ Asian   │ Not Hispanic or Latino │ 10000473    │ NULL     │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 8e2af9ea-eeab-583d-a87d-3cf218d2b6ea │ Patient_10000492 │ male    │ 2107-08-04 │ White   │ Not Hispanic or Latino │ 10000492    │ NULL     │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
├──────────────────────────────────────┴──────────────────┴─────────┴────────────┴─────────┴────────────────────────┴─────────────┴──────────┴────────────────┴──────────────────────────────────────┤
│ 10 rows                                                                                                                                                                                 10 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [87]:
# Test silver.patient
con.sql("SELECT * FROM silver.patient LIMIT 10;")

┌──────────────────────────────────────┬──────────────────┬─────────┬────────────┬─────────┬────────────────────────┬─────────────┬──────────┬────────────────┬──────────────────────────────────────┐
│             resource_id              │       name       │ gender  │ birth_date │  race   │       ethnicity        │ patient_num │ language │ marital_status │           organization_id            │
│               varchar                │     varchar      │ varchar │  varchar   │ varchar │        varchar         │   varchar   │ varchar  │    varchar     │               varchar                │
├──────────────────────────────────────┼──────────────────┼─────────┼────────────┼─────────┼────────────────────────┼─────────────┼──────────┼────────────────┼──────────────────────────────────────┤
│ 7d101f5f-aba3-586c-94b2-6055c90992a2 │ Patient_15173979 │ male    │ 2072-02-02 │ unknown │ NULL                   │ 15173979    │ en       │ S              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ a086c42a-3a93-5e8e-ba65-7472c3835538 │ Patient_15174025 │ male    │ 2126-08-29 │ White   │ Not Hispanic or Latino │ 15174025    │ NULL     │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 3437ec4b-3090-5264-bead-a99e744e6a00 │ Patient_15174063 │ female  │ 2156-11-11 │ unknown │ NULL                   │ 15174063    │ en       │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ ac8edad5-3e0b-5964-9602-9ae1933e01e5 │ Patient_15174098 │ female  │ 2144-03-09 │ White   │ Not Hispanic or Latino │ 15174098    │ NULL     │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ f040bdf0-6951-5194-a400-fac7a247583c │ Patient_15174162 │ female  │ 2110-02-08 │ Asian   │ Not Hispanic or Latino │ 15174162    │ NULL     │ M              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ b219326e-92d9-5ac4-b9f1-8f0e8e6516b8 │ Patient_15174186 │ male    │ 2053-01-26 │ White   │ Not Hispanic or Latino │ 15174186    │ en       │ M              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 28fea5da-0446-520f-b85a-dd6122c95366 │ Patient_15174216 │ male    │ 2076-02-02 │ White   │ Not Hispanic or Latino │ 15174216    │ en       │ M              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 6c790d68-2be9-5f9c-a48d-4bff38570231 │ Patient_15174295 │ male    │ 2106-03-19 │ White   │ Not Hispanic or Latino │ 15174295    │ NULL     │ UNK            │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ 9bd28d0b-a196-50ee-8186-0c348d7cef36 │ Patient_15174306 │ female  │ 2080-12-28 │ White   │ Not Hispanic or Latino │ 15174306    │ en       │ M              │ ee172322-118b-5716-abbc-18e4c5437e15 │
│ e23f6801-37d3-55f3-afe4-4bd8bb1885fb │ Patient_15174548 │ male    │ 2130-07-22 │ White   │ Not Hispanic or Latino │ 15174548    │ en       │ M              │ ee172322-118b-5716-abbc-18e4c5437e15 │
├──────────────────────────────────────┴──────────────────┴─────────┴────────────┴─────────┴────────────────────────┴─────────────┴──────────┴────────────────┴──────────────────────────────────────┤
│ 10 rows                                                                                                                                                                                 10 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

---

## Silver & Gold tables

Exploring Silver and Gold (mart) tables

In [20]:
# silver.obs_vital
con.sql("""
  SELECT *
  FROM silver.obs_vitals
  LIMIT 10
""")

┌──────────────────────────────────────┬──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬────────────┬────────┬────────────────┐
│             resource_id              │              patient_id              │             encounter_id             │ effective_datetime  │ loinc_code │ value  │      unit      │
│               varchar                │               varchar                │               varchar                │      timestamp      │  varchar   │ double │    varchar     │
├──────────────────────────────────────┼──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼────────────┼────────┼────────────────┤
│ e6944724-62ed-53df-b56e-f26d77f8fc14 │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 17:35:00 │ 9279-1     │   18.0 │ breaths/minute │
│ 0df7928c-9982-5ca9-ab43-b965e5ec275f │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 22:55:00 │ 8867-4     │   92.0 │ beats/minute   │
│ 140a6ebd-8e2d-5ae5-9af1-605f430714d3 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 15:42:00 │ 8310-5     │   NULL │ NULL           │
│ fd57fed8-0459-512b-8350-d0b13a51421c │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 19:46:00 │ 2708-6     │   97.0 │ %              │
│ 82ccbb99-eb1a-5261-8ee0-ce5de2d044c8 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 19:46:00 │ 8310-5     │   98.1 │ F              │
│ 5e9ecd5f-4228-54a1-8b17-e163c2464c91 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 21:43:00 │ 9279-1     │   16.0 │ breaths/minute │
│ 77526c5e-4744-549d-b5d0-529b4b806618 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 22:02:00 │ 8310-5     │   NULL │ NULL           │
│ 5a0c8b1d-0c24-5515-8297-abb31fd217f2 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-25 02:02:00 │ 2708-6     │   99.0 │ %              │
│ 9823d5c7-09e5-58fe-95f6-bfaa722fdc11 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-25 02:02:00 │ 8867-4     │   76.0 │ beats/minute   │
│ 3d125d90-6611-5005-8f1d-431e03520ddd │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-25 06:31:00 │ 9279-1     │   16.0 │ breaths/minute │
├──────────────────────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴────────────┴────────┴────────────────┤
│ 10 rows                                                                                                                                                               7 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
# intermediate.vitals_wide
con.sql("SELECT * FROM intermediate.vitals_wide LIMIT 10")

┌──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬────────────┬──────────┬──────────┬────────────┬───────────┬───────────┬──────────────┬────────────┬────────────┬──────────────┬─────────────┬─────────────┐
│             encounter_id             │              patient_id              │ effective_datetime  │ temp_value │ hr_value │ rr_value │ spo2_value │ sbp_value │ dbp_value │ temp_present │ hr_present │ rr_present │ spo2_present │ sbp_present │ dbp_present │
│               varchar                │               varchar                │      timestamp      │   double   │  double  │  double  │   double   │  double   │  double   │    int32     │   int32    │   int32    │    int32     │    int32    │    int32    │
├──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼────────────┼──────────┼──────────┼────────────┼───────────┼───────────┼──────────────┼────────────┼────────────┼──────────────┼─────────────┼─────────────┤
│ b8a497c2-7a67-56b0-b078-9b1f3f6c0a06 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2172-05-04 23:36:00 │       NULL │     93.0 │     18.0 │       98.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 75dd8f71-58a4-5a7d-a9da-79f9bc59f139 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2171-10-29 20:47:00 │       99.5 │    111.0 │     20.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ d729a6fb-a212-5996-a5b3-c0fdf348d135 │ fb3949fe-6ae8-575d-b8c2-5d44b414c27c │ 2174-07-27 15:52:00 │       98.1 │     76.0 │     18.0 │       98.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 0fa52380-fe25-5e0e-87aa-5a035dca5233 │ fb48c521-09d6-52d4-99b3-545db8e101b5 │ 2175-05-03 18:41:00 │       NULL │     74.0 │     18.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 413eb62c-13a2-5518-a4a3-4fdca697ef44 │ fb70b4a9-4bba-592c-9c8a-679c9266550d │ 2121-03-01 17:24:00 │       97.5 │     89.0 │     17.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ c594dbe1-635c-5ab4-ad4b-3b38df820f64 │ fb751c9d-0ce3-5371-96bf-dcd0578dae53 │ 2116-08-01 17:54:00 │       97.5 │     92.0 │     18.0 │       97.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 0fae3e9c-d7bb-532d-9b6a-538dc35beb22 │ fb775840-629a-54cb-a30f-1ec55874e9fc │ 2146-05-31 04:50:00 │       97.0 │     78.0 │     19.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ e9fa8536-dbb5-5fde-9c7e-c9e47a90a6d0 │ fb8a8009-ad7b-590c-b1c6-a937e48a7411 │ 2189-06-28 06:51:00 │       97.2 │     62.0 │     18.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 66be00e5-f354-5f6f-b829-360a3296eeba │ fb8aaeb8-08d0-5821-aca4-aa2393893d7e │ 2135-10-19 17:10:00 │       98.2 │     60.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 1a2025ce-b334-5632-9cee-38426bf21d8e │ fb8b131d-2af0-5415-b620-5105acb33ba9 │ 2180-11-01 18:20:00 │       98.6 │     70.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
├──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴────────────┴──────────┴──────────┴────────────┴───────────┴───────────┴──────────────┴────────────┴────────────┴──────────────┴─────────────┴─────────────┤
│ 10 rows                                                                                                                                                                                                                                            15 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [17]:
con.sql("""
  SELECT * 
  FROM intermediate.vitals_wide
  WHERE patient_id='fb348f58-e2e7-5fab-8118-494943e3b84b'
  ORDER BY effective_datetime DESC
  LIMIT 10
""")

┌──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬────────────┬──────────┬──────────┬────────────┬───────────┬───────────┬──────────────┬────────────┬────────────┬──────────────┬─────────────┬─────────────┐
│             encounter_id             │              patient_id              │ effective_datetime  │ temp_value │ hr_value │ rr_value │ spo2_value │ sbp_value │ dbp_value │ temp_present │ hr_present │ rr_present │ spo2_present │ sbp_present │ dbp_present │
│               varchar                │               varchar                │      timestamp      │   double   │  double  │  double  │   double   │  double   │  double   │    int32     │   int32    │   int32    │    int32     │    int32    │    int32    │
├──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼────────────┼──────────┼──────────┼────────────┼───────────┼───────────┼──────────────┼────────────┼────────────┼──────────────┼─────────────┼─────────────┤
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 22:16:00 │       98.4 │     93.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 22:04:00 │       NULL │    110.0 │     NULL │       NULL │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 20:59:00 │       98.4 │    120.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 20:49:00 │       98.2 │     99.0 │     18.0 │       98.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 19:05:00 │       98.1 │     98.0 │     16.0 │       98.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 15:23:00 │       98.2 │    114.0 │     16.0 │       95.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 15:21:00 │       98.2 │    114.0 │     16.0 │       95.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ fcda92e5-4158-52c6-9464-bda0d1ad7dc5 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2172-11-25 07:23:00 │       97.9 │     89.0 │     15.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ fcda92e5-4158-52c6-9464-bda0d1ad7dc5 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2172-11-25 05:38:00 │       98.3 │     94.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ fcda92e5-4158-52c6-9464-bda0d1ad7dc5 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2172-11-25 02:10:00 │       NULL │     82.0 │     16.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
├──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴────────────┴──────────┴──────────┴────────────┴───────────┴───────────┴──────────────┴────────────┴────────────┴──────────────┴─────────────┴─────────────┤
│ 10 rows                                                                                                                                                                                                                                            15 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [3]:
# marts.vitals_eda
con.sql("""
  SELECT *
  FROM marts.vitals_eda
  LIMIT 10
""")

┌──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬────────────┬──────────┬──────────┬────────────┬───────────┬───────────┬──────────────┬────────────┬────────────┬──────────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬─────────────┬─────────────┬──────────────┬────────────────────────┬───────────┬────────────────────────┬─────────────────┐
│             encounter_id             │              patient_id              │ effective_datetime  │ temp_value │ hr_value │ rr_value │ spo2_value │ sbp_value │ dbp_value │ temp_present │ hr_present │ rr_present │ spo2_present │ sbp_present │ dbp_present │ n_vitals_6 │ n_vitals_5 │ n_vitals_3 │ hour_of_day │ day_of_week │ obs_position │ total_obs_in_encounter │ delta_min │ encounter_duration_hrs │ encounter_phase │
│               varchar                │               varchar                │      timestamp      │   double   │  double  │  double  │   double   │  double   │  double   │    int32     │   int32    │   int32    │    int32     │    int32    │    int32    │   int32    │   int32    │   int32    │    int64    │    int64    │    int64     │         int64          │  double   │         double         │     varchar     │
├──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼────────────┼──────────┼──────────┼────────────┼───────────┼───────────┼──────────────┼────────────┼────────────┼──────────────┼─────────────┼─────────────┼────────────┼────────────┼────────────┼─────────────┼─────────────┼──────────────┼────────────────────────┼───────────┼────────────────────────┼─────────────────┤
│ b796d42d-11c4-5a7a-af22-e7e711d6ce9b │ 01593ff8-6440-5ca4-94c5-a622232b8e87 │ 2133-10-11 16:23:00 │       NULL │     82.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          16 │           0 │            3 │                      4 │     147.0 │      7.866666666666666 │ Late            │
│ b796d42d-11c4-5a7a-af22-e7e711d6ce9b │ 01593ff8-6440-5ca4-94c5-a622232b8e87 │ 2133-10-11 21:47:00 │       98.6 │     81.0 │     18.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          21 │           0 │            4 │                      4 │     324.0 │      7.866666666666666 │ Late            │
│ b7989659-0779-5767-aed3-7f3057594a67 │ a5288459-4c42-5ed0-b542-c2a2a857f17d │ 2144-10-23 16:07:00 │       98.7 │    122.0 │     20.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          16 │           5 │            1 │                      4 │      NULL │      6.366666666666666 │ Early           │
│ b7989659-0779-5767-aed3-7f3057594a67 │ a5288459-4c42-5ed0-b542-c2a2a857f17d │ 2144-10-23 16:09:00 │       98.7 │    122.0 │     20.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          16 │           5 │            2 │                      4 │       2.0 │      6.366666666666666 │ Middle          │
│ b7989659-0779-5767-aed3-7f3057594a67 │ a5288459-4c42-5ed0-b542-c2a2a857f17d │ 2144-10-23 20:05:00 │       98.9 │     90.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          20 │           5 │            3 │                      4 │     236.0 │      6.366666666666666 │ Late            │
│ b7989659-0779-5767-aed3-7f3057594a67 │ a5288459-4c42-5ed0-b542-c2a2a857f17d │ 2144-10-23 22:29:00 │       98.8 │     89.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          22 │           5 │            4 │                      4 │     144.0 │      6.366666666666666 │ Late            │
│ b79ca346-7714-51ef-8184-04504641e29b │ 1febffc4-76e6-58f3-8db5-0f7ccaa169ba │ 2168-05-23 21:06:00 │       97.8 │     81.0 │     19.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          21 │           1 │            1 │                      2 │      NULL │     1.7333333333333334 │ Middle          │
│ b79ca346-7714-51ef-8184-04504641e29b │ 1febffc4-76e6-58f3-8db5-0f7ccaa169ba │ 2168-05-23 22:50:00 │       98.0 │     85.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          22 │           1 │            2 │                      2 │     104.0 │     1.7333333333333334 │ Late            │
│ b79de50f-f5eb-54d5-b7c9-744abe34bc45 │ 6f100882-9b00-570e-989e-9ee9e6679862 │ 2135-05-06 15:35:00 │       98.5 │     99.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          15 │           5 │            1 │                      1 │      NULL │                    0.0 │ Late            │
│ b7a2c727-4a0c-5237-8a66-fc5ccee37aee │ a52eadae-df23-53af-b216-79e16233e26c │ 2152-11-20 10:39:00 │       99.7 │    135.0 │     16.0 │       NULL │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          10 │           1 │            1 │                      5 │      NULL │                   4.05 │ Early           │
├──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴────────────┴──────────┴──────────┴────────────┴───────────┴───────────┴──────────────┴────────────┴────────────┴──────────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴─────────────┴─────────────┴──────────────┴────────────────────────┴───────────┴────────────────────────┴─────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                              25 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [5]:
con.sql("SELECT * FROM bronze.fhir_resources LIMIT 10")

┌───────────────┬──────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────┐
│ resource_type │             resource_id              │                                                                                                                                                                                                                                                                            resource                                                                                                                                                                                                                                                                            │    source_file     │
│    varchar    │               varchar                │                                                                                                                                                                                                                                                                            varchar                                                                                                                                                                                                                                                                             │      varchar       │
├───────────────┼──────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────┤
│ Procedure     │ ef1cc99a-f637-5480-b646-0526caa35b16 │ {"id": "ef1cc99a-f637-5480-b646-0526caa35b16", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9"}, "resourceType": "Procedure", "performedDateTime": "2169-10-24T15:42:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 2c9e78fd-57c1-5665-98e2-a90e11cd12bd │ {"id": "2c9e78fd-57c1-5665-98e2-a90e11cd12bd", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9"}, "resourceType": "Procedure", "performedDateTime": "2169-10-24T09:59:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 4fe0eae4-4ce2-5251-83d0-d11475806507 │ {"id": "4fe0eae4-4ce2-5251-83d0-d11475806507", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/ab67e413-be5f-5c55-97d2-615c1941d950"}, "resourceType": "Procedure", "performedDateTime": "2169-09-06T22:55:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 54432192-06f6-5ac4-b329-5e0c1ec2ddcf │ {"id": "54432192-06f6-5ac4-b329-5e0c1ec2ddcf", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/ab67e413-be5f-5c55-97d2-615c1941d950"}, "resourceType": "Procedure", "performedDateTime": "2169-09-06T17:35:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 91218afd-ab8b-5ed9-88c8-fadb6cffb90e │ {"id": "91218afd-ab8b-5ed9-88c8-fadb6cffb90e", "code": {"coding": [{"code": "386478007", "system": "http://snomed.info/sct", "display": "Triage: emergency center (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9"}, "resourceType": "Procedure", "performedDateTime": "2169-10-24T09:57:00-04:00"}              │ ProcedureED.ndjson │
│ Procedure     │ 34f170a9-d41b-5176-8b71-39a7aa353815 │ {"id": "34f170a9-d41b-5176-8b71-39a7aa353815", "code": {"coding": [{"code": "386478007", "system": "http://snomed.info/sct", "display": "Triage: emergency center (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/ab67e413-be5f-5c55-97d2-615c1941d950"}, "resourceType": "Procedure", "performedDateTime": "2169-09-06T17:34:00-04:00"}              │ ProcedureED.ndjson │
│ Procedure     │ 69c338ec-d271-5b60-acdb-4014a661cd3f │ {"id": "69c338ec-d271-5b60-acdb-4014a661cd3f", "code": {"coding": [{"code": "386478007", "system": "http://snomed.info/sct", "display": "Triage: emergency center (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/3fee1b6e-f877-5bf0-ae81-f69ee2adc4fe"}, "resourceType": "Procedure", "performedDateTime": "2165-10-01T15:51:00-04:00"}              │ ProcedureED.ndjson │
│ Procedure     │ c54a56d7-0a95-5395-a9d1-a1d915ef7784 │ {"id": "c54a56d7-0a95-5395-a9d1-a1d915ef7784", "code": {"coding": [{"code": "386478007", "system": "http://snomed.info/sct", "display": "Triage: emergency center (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/8178aca7-ebbc-53db-a425-4f9a5c25786b"}, "resourceType": "Procedure", "performedDateTime": "2169-10-08T18:39:00-04:00"}              │ ProcedureED.ndjson │
│ Procedure     │ 21527095-eb3a-590d-8a51-9f915c7c95b6 │ {"id": "21527095-eb3a-590d-8a51-9f915c7c95b6", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/8178aca7-ebbc-53db-a425-4f9a5c25786b"}, "resourceType": "Procedure", "performedDateTime": "2169-10-08T20:57:00-04:00"} │ ProcedureED.ndjson │
│ Procedure     │ 11333007-4b3a-5092-8fc2-b39888bdc2aa │ {"id": "11333007-4b3a-5092-8fc2-b39888bdc2aa", "code": {"coding": [{"code": "410188000", "system": "http://snomed.info/sct", "display": "Taking patient vital signs assessment (procedure)"}]}, "meta": {"profile": ["http://mimic.mit.edu/fhir/mimic/StructureDefinition/mimic-procedure-ed"]}, "status": "completed", "subject": {"reference": "Patient/000000ba-735e-5858-a92d-b856d73dd69a"}, "encounter": {"reference": "Encounter/8178aca7-ebbc-53db-a425-4f9a5c25786b"}, "resourceType": "Procedure", "performedDateTime": "2169-10-08T18:41:00-04:00"} │ ProcedureED.ndjson │
├───────────────┴──────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          4 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

---

# Synthea Data

Flattening Synthea data into a workable format

In [1]:
import duckdb
import os
from dotenv import load_dotenv

load_dotenv()

False

In [2]:
con = duckdb.connect("../data/warehouse/mimic_fhir.duckdb")

In [5]:
con.sql("SELECT DISTINCT resource_type FROM bronze.synthea;")

┌──────────────────────────┐
│      resource_type       │
│         varchar          │
├──────────────────────────┤
│ ExplanationOfBenefit     │
│ Observation              │
│ ImagingStudy             │
│ Encounter                │
│ DiagnosticReport         │
│ Immunization             │
│ CarePlan                 │
│ MedicationAdministration │
│ DocumentReference        │
│ Provenance               │
│ SupplyDelivery           │
│ Condition                │
│ Procedure                │
│ Medication               │
│ Device                   │
│ AllergyIntolerance       │
│ MedicationRequest        │
│ Patient                  │
│ Claim                    │
│ CareTeam                 │
├──────────────────────────┤
│         20 rows          │
└──────────────────────────┘

In [6]:
con.sql("SELECT * FROM bronze.synthea WHERE resource_type='Patient' LIMIT 10;")

┌───────────────────────────────────────────────┬───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────┬───────────────────────────────────┬──────────────────────────────────────┐
│                   full_url                    │ resource_type │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              resource                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              │              request              │            source_file            │               file_id                │
│                    varchar                    │    varchar    │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                json                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │               json                │              varchar              │               varchar                │

## 1. Patient

In [16]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->'name'->0->'given'->>0 AS first_name,
    resource->'name'->0->'given'->>1 AS middle_name,
    resource->'name'->0->>'family' AS last_name,
    resource->>'gender' AS gender,
    resource->'extension'->0->'extension'->0->'valueCoding'->>'display' AS race,
    resource->'extension'->1->'extension'->1->>'valueString' AS ethnicity,
    resource->>'birthDate' AS birth_date,
    resource->'telecom'->0->>'value' AS phone_number,
    resource->'maritalStatus'->>'text' AS marital_status,
    resource->'address'->0->>'city' AS city,
    resource->'address'->0->>'state' AS state,
    resource->'address'->0->>'country' AS country,
    resource->'address'->0->'line'->>0 AS street_address,
    TRY_CAST(resource->'address'->0->'extension'->0->'extension'->0->'valueDecimal' AS DOUBLE) AS latitude,
    TRY_CAST(resource->'address'->0->'extension'->0->'extension'->1->'valueDecimal' AS DOUBLE) AS longitude,
    TRY_CAST(resource->'extension'->5->'valueDecimal' AS DOUBLE) AS disablility_adjusted_life_years,
    TRY_CAST(resource->'extension'->6->'valueDecimal' AS DOUBLE) AS quality_adjusted_life_years
  FROM bronze.synthea
  WHERE resource_type='Patient';
""")

┌──────────────────────────────────────┬─────────────┬─────────────┬────────────┬─────────┬───────────────────────────────────────────┬────────────────────────┬────────────┬──────────────┬────────────────┬──────────────────┬─────────┬─────────┬───────────────────────────────────────┬────────────────────┬────────────────────┬─────────────────────────────────┬─────────────────────────────┐
│             resource_id              │ first_name  │ middle_name │ last_name  │ gender  │                   race                    │       ethnicity        │ birth_date │ phone_number │ marital_status │       city       │  state  │ country │            street_address             │      latitude      │     longitude      │ disablility_adjusted_life_years │ quality_adjusted_life_years │
│               varchar                │   varchar   │   varchar   │  varchar   │ varchar │                  varchar                  │        varchar         │  varchar   │   varchar    │    varchar     │     varchar      │ varchar │ varchar │                varchar                │       double       │       double       │             double              │           double            │
├──────────────────────────────────────┼─────────────┼─────────────┼────────────┼─────────┼───────────────────────────────────────────┼────────────────────────┼────────────┼──────────────┼────────────────┼──────────────────┼─────────┼─────────┼───────────────────────────────────────┼────────────────────┼────────────────────┼─────────────────────────────────┼─────────────────────────────┤
│ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ Ignacio928  │ Felipe97    │ Saiz247    │ male    │ White                                     │ Hispanic or Latino     │ 1975-06-15 │ 555-802-1529 │ Married        │ Wilbraham        │ MA      │ US      │ 580 Schowalter Frontage road Suite 83 │  42.15142184176261 │  -72.3809130083142 │            0.023573544605080224 │           49.97642645539492 │
│ 2e312e34-cc56-6a67-6642-c261c2f4838f │ Savannah232 │ Kathryne752 │ Glover433  │ female  │ Native Hawaiian or Other Pacific Islander │ Hispanic or Latino     │ 1962-10-16 │ 555-519-4931 │ Married        │ Somerville       │ MA      │ US      │ 369 Schneider Lane Apt 74             │ 42.406632386263055 │ -71.10223470844319 │               4.459627623015047 │          58.540372376984955 │
│ a3d61946-69d4-cd45-0792-f8b941bd6f73 │ Evia329     │ Carletta836 │ Brown30    │ female  │ White                                     │ Not Hispanic or Latino │ 2000-05-08 │ 555-283-4222 │ Never Married  │ Deerfield        │ MA      │ US      │ 1035 Koepp Lodge                      │  42.49866140347856 │  -72.6236341086998 │              0.7463814140652552 │          24.253618585934746 │
│ 7a1179d0-2872-0404-1d16-d547ec695539 │ Alisa860    │ Melisa53    │ Collier206 │ female  │ White                                     │ Not Hispanic or Latino │ 2001-05-07 │ 555-892-3971 │ Never Married  │ Medford          │ MA      │ US      │ 149 Beier Station Unit 96             │  42.43030509110423 │ -71.14183517535145 │           0.0030497205673112576 │           23.99695027943269 │
│ 65c8b696-d584-040e-c6b5-8a0650051e8e │ Michele387  │ Diana207    │ Nader710   │ female  │ Native Hawaiian or Other Pacific Islander │ Hispanic or Latino     │ 1962-10-16 │ 555-987-1712 │ Married        │ Somerville       │ MA      │ US      │ 443 Kihn Rapid Apt 16                 │  42.34934062511945 │ -71.09801466679099 │             0.09304239412489822 │            60.9069576058751 │
│ b5a392cb-15fa-83c1-8795-9da5075a7968 │ Gale827     │ NULL        │ Quitzon246 │ male    │ White                                     │ Not Hispanic or Latino │ 1962-10-27 │ 555-996-8908 │ Widowed        │ Great Barrington │ MA      │ US      │ 403 Marvin Hollow                     │  42.24223185570958 │ -73.30902119713589 │              0.5327093011183273 │           62.46729069888167 │
│ e24409c6-2407-91cb-8ff2-ccfb74085e7b │ Vaughn909   │ Chung121    │ Farrell962 │ male    │ White                                     │ Not Hispanic or Latino │ 1962-10-27 │ 555-744-5393 │ Widowed        │ Great Barrington │ MA      │ US      │ 183 Emard Lodge Suite 56              │ 42.271221080210026 │ -73.37403710086667 │              0.8193276034412107 │           55.18067239655879 │
└──────────────────────────────────────┴─────────────┴─────────────┴────────────┴─────────┴───────────────────────────────────────────┴────────────────────────┴────────────┴──────────────┴────────────────┴──────────────────┴─────────┴─────────┴───────────────────────────────────────┴────────────────────┴────────────────────┴─────────────────────────────────┴─────────────────────────────┘

## 2. Observation

Information extracted from patients

In [24]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->>'status' AS status,
    resource->'category'->0->'coding'->0->>'code' AS record,
    resource->'code'->'coding'->0->>'code' AS measure_code,
    resource->'code'->'coding'->0->>'display' AS measure_name,
    TRY_CAST(
      CASE WHEN resource->'valueQuantity'->>'value' IS NOT NULL
      THEN resource->'valueQuantity'->>'value'
      ELSE resource->'component'->0->'valueQuantity'->>'value' END AS DOUBLE
    ) AS value,
    CASE WHEN resource->'valueQuantity'->>'unit' IS NOT NULL THEN resource->'valueQuantity'->>'unit' ELSE resource->'component'->0->'valueQuantity'->>'unit' END AS unit,
    regexp_replace(resource->'subject'->>'reference', 'urn:uuid:', '') AS patient_id,
    (resource->>'effectiveDateTime')::TIMESTAMP AS effective_timestamp,
    (resource->>'issued')::TIMESTAMP AS issued_timestamp
  FROM bronze.synthea
  WHERE resource_type='Observation'
  LIMIT 50;
""")

┌──────────────────────────────────────┬─────────┬────────────────┬──────────────┬──────────────────────────────────────────────────────────────────────────┬────────┬─────────┬──────────────────────────────────────┬─────────────────────┬─────────────────────────┐
│             resource_id              │ status  │     record     │ measure_code │                               measure_name                               │ value  │  unit   │              patient_id              │ effective_timestamp │    issued_timestamp     │
│               varchar                │ varchar │    varchar     │   varchar    │                                 varchar                                  │ double │ varchar │               varchar                │      timestamp      │        timestamp        │
├──────────────────────────────────────┼─────────┼────────────────┼──────────────┼──────────────────────────────────────────────────────────────────────────┼────────┼─────────┼──────────────────────────────────────┼─────────────────────┼─────────────────────────┤
│ 24283ca3-2f37-a4c1-4c57-0042ad28eb13 │ final   │ vital-signs    │ 8302-2       │ Body Height                                                              │  180.2 │ cm      │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-3397-90f18c113f90 │ final   │ vital-signs    │ 72514-3      │ Pain severity - 0-10 verbal numeric rating [Score] - Reported            │    1.0 │ {score} │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-4f7f-73dfdf4c1ba3 │ final   │ vital-signs    │ 29463-7      │ Body Weight                                                              │   89.4 │ kg      │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-7e1d-7261eaa7a4d9 │ final   │ vital-signs    │ 39156-5      │ Body mass index (BMI) [Ratio]                                            │  27.53 │ kg/m2   │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-24fa-745a889b8fba │ final   │ vital-signs    │ 85354-9      │ Blood pressure panel with all children optional                          │   79.0 │ mm[Hg]  │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-cdd5-ca8d51efea9a │ final   │ vital-signs    │ 8867-4       │ Heart rate                                                               │   80.0 │ /min    │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-d39c-f9cade2c429d │ final   │ vital-signs    │ 9279-1       │ Respiratory rate                                                         │   13.0 │ /min    │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-e4ba-e8c493ada2ec │ final   │ laboratory     │ 2093-3       │ Cholesterol [Mass/volume] in Serum or Plasma                             │ 138.58 │ mg/dL   │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-6819-459615ded06a │ final   │ laboratory     │ 2571-8       │ Triglyceride [Mass/volume] in Serum or Plasma                            │  143.3 │ mg/dL   │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│ 24283ca3-2f37-a4c1-2283-c3b78fc46fe9 │ final   │ laboratory     │ 18262-6      │ Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay      │  53.16 │ mg/dL   │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2017-06-25 02:35:45 │ 2017-06-25 02:35:45.754 │
│                  ·                   │   ·     │     ·          │   ·          │                 ·                                                        │    ·   │  ·      │                  ·                   │          ·          │            ·            │
│                  ·                   │   ·     │     ·          │   ·          │                 ·                                                        │    ·   │  ·      │                  ·                   │          ·          │            ·            │
│                  ·                   │   ·     │     ·          │   ·          │                 ·                                                        │    ·   │  ·      │                  ·                   │          ·          │            ·            │
│ 24283ca3-2f37-a4c1-4958-2f8e95115ff4 │ final   │ laboratory     │ 718-7        │ Hemoglobin [Mass/volume] in Blood                                        │ 15.691 │ g/dL    │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-2f7f-063ee056b4ce │ final   │ laboratory     │ 4544-3       │ Hematocrit [Volume Fraction] of Blood by Automated count                 │ 35.889 │ %       │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-3c50-4ff25c01955b │ final   │ laboratory     │ 787-2        │ MCV [Entitic mean volume] in Red Blood Cells by Automated count          │ 91.711 │ fL      │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-2894-cc3234bc688f │ final   │ laboratory     │ 785-6        │ MCH [Entitic mass] by Automated count                                    │ 31.707 │ pg      │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-2b99-76fdcc549136 │ final   │ laboratory     │ 786-4        │ MCHC [Entitic Mass/volume] in Red Blood Cells by Automated count         │ 35.424 │ g/dL    │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-11f6-31f10d76ca49 │ final   │ laboratory     │ 788-0        │ Erythrocyte [DistWidth] in Blood by Automated count                      │ 42.244 │ fL      │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-47b3-5ba2cbe47483 │ final   │ laboratory     │ 777-3        │ Platelets [#/volume] in Blood by Automated count                         │ 173.84 │ 10*3/uL │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-f926-f94e1137a932 │ final   │ laboratory     │ 32207-3      │ Platelet distribution width [Entitic volume] in Blood by Automated count │ 304.08 │ fL      │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-b848-56b3c1552652 │ final   │ laboratory     │ 32623-1      │ Platelet [Entitic mean volume] in Blood by Automated count               │ 11.464 │ fL      │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
│ 24283ca3-2f37-a4c1-f6c3-403fac0867d7 │ final   │ social-history │ 72166-2      │ Tobacco smoking status                                                   │   NULL │ NULL    │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 2021-07-04 02:35:45 │ 2021-07-04 02:35:45.754 │
├──────────────────────────────────────┴─────────┴────────────────┴──────────────┴──────────────────────────────────────────────────────────────────────────┴────────┴─────────┴──────────────────────────────────────┴─────────────────────┴─────────────────────────┤
│ 50 rows (20 shown)                                                                                                                                                                                                                                       10 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## 3. Encounter

In [31]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->>'status' AS status,
    resource->'class'->>'code' AS class,
    resource->'type'->0->'coding'->0->>'code' AS procedure_code,
    regexp_replace(resource->'type'->0->'coding'->0->>'display', ' \(procedure\)', '') AS procedure_name,
    regexp_replace(resource->'subject'->>'reference', 'urn:uuid:', '') AS patient_id,
    resource->'participant'->0->'type'->0->'coding'->0->>'code' AS practitioner_code,
    resource->'participant'->0->'type'->0->'coding'->0->>'display' AS practitioner_type,
    split_part(resource->'participant'->0->'individual'->>'reference', '|', 2) AS practitioner_id,
    resource->'participant'->0->'individual'->>'display' AS practitioner_name,
    (resource->'period'->>'start')::TIMESTAMP AS start_date,
    (resource->'period'->>'end')::TIMESTAMP AS end_date,
    split_part(resource->'location'->0->'location'->>'reference', '|', 2) AS location_id,
    resource->'location'->0->'location'->>'display' AS location_name,
    split_part(resource->'serviceProvider'->>'reference', '|', 2) AS provider_id,
    resource->'serviceProvider'->>'display' AS provider_name,
  FROM bronze.synthea
  WHERE resource_type='Encounter'
  LIMIT 10;
""")

┌──────────────────────────────────────┬──────────┬─────────┬────────────────┬────────────────────────────────┬──────────────────────────────────────┬───────────────────┬───────────────────┬─────────────────┬──────────────────────────────┬─────────────────────┬─────────────────────┬──────────────────────────────────────┬────────────────────────────────────┬──────────────────────────────────────┬────────────────────────────────────┐
│             resource_id              │  status  │  class  │ procedure_code │         procedure_name         │              patient_id              │ practitioner_code │ practitioner_type │ practitioner_id │      practitioner_name       │     start_date      │      end_date       │             location_id              │           location_name            │             provider_id              │           provider_name            │
│               varchar                │ varchar  │ varchar │    varchar     │            varchar             │               varchar                │      varchar      │      varchar      │     varchar     │           varchar            │      timestamp      │      timestamp      │               varchar                │              varchar               │               varchar                │              varchar               │
├──────────────────────────────────────┼──────────┼─────────┼────────────────┼────────────────────────────────┼──────────────────────────────────────┼───────────────────┼───────────────────┼─────────────────┼──────────────────────────────┼─────────────────────┼─────────────────────┼──────────────────────────────────────┼────────────────────────────────────┼──────────────────────────────────────┼────────────────────────────────────┤
│ 24283ca3-2f37-a4c1-84b9-f7ffa9da3120 │ finished │ AMB     │ 162673000      │ General examination of patient │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999942896      │ Dr. Arla414 Fritsch593       │ 1993-08-08 02:35:45 │ 1993-08-08 03:05:47 │ a3d9fbb2-8e79-3105-8bf0-ccd519a97ca2 │ RIVER'S EDGE PRIMARY CARE LLC      │ aad05540-c9cb-3805-b3c4-f9b9d9b42b2e │ RIVER'S EDGE PRIMARY CARE LLC      │
│ 24283ca3-2f37-a4c1-b6de-137c628f8ba9 │ finished │ AMB     │ 185349003      │ Encounter for check up         │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999991893      │ Dr. Samuel331 Villalpando154 │ 2006-06-25 02:35:45 │ 2006-06-25 03:26:20 │ 7771ffe2-9f78-3914-ae55-ce0d6a3ccba0 │ BAYSTATE WING HOSPITAL CORPORATION │ 46375470-1e20-3ddc-8dc5-010ba53826b6 │ BAYSTATE WING HOSPITAL CORPORATION │
│ 24283ca3-2f37-a4c1-c080-c4d2a4544d68 │ finished │ AMB     │ 162673000      │ General examination of patient │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999942896      │ Dr. Arla414 Fritsch593       │ 2015-06-21 02:35:45 │ 2015-06-21 03:28:54 │ a3d9fbb2-8e79-3105-8bf0-ccd519a97ca2 │ RIVER'S EDGE PRIMARY CARE LLC      │ aad05540-c9cb-3805-b3c4-f9b9d9b42b2e │ RIVER'S EDGE PRIMARY CARE LLC      │
│ 24283ca3-2f37-a4c1-2739-f37048c77046 │ finished │ AMB     │ 162673000      │ General examination of patient │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999942896      │ Dr. Arla414 Fritsch593       │ 2017-06-25 02:35:45 │ 2017-06-25 03:35:21 │ a3d9fbb2-8e79-3105-8bf0-ccd519a97ca2 │ RIVER'S EDGE PRIMARY CARE LLC      │ aad05540-c9cb-3805-b3c4-f9b9d9b42b2e │ RIVER'S EDGE PRIMARY CARE LLC      │
│ 24283ca3-2f37-a4c1-647f-aae0d05afacd │ finished │ EMER    │ 50849002       │ Emergency room admission       │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999900399      │ Dr. Sid118 Wilderman619      │ 2019-01-12 02:35:45 │ 2019-01-12 03:35:45 │ 32bb0f99-ac43-3c94-8dc5-3468f92b3bc9 │ LIFE CARE CENTER OF WILBRAHAM      │ e1818b21-4458-3b9c-b2b8-7ed6f57ae078 │ LIFE CARE CENTER OF WILBRAHAM      │
│ 24283ca3-2f37-a4c1-9c6b-581692c168ba │ finished │ AMB     │ 185349003      │ Encounter for check up         │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999991893      │ Dr. Samuel331 Villalpando154 │ 2019-02-14 02:35:45 │ 2019-02-14 02:50:45 │ 7771ffe2-9f78-3914-ae55-ce0d6a3ccba0 │ BAYSTATE WING HOSPITAL CORPORATION │ 46375470-1e20-3ddc-8dc5-010ba53826b6 │ BAYSTATE WING HOSPITAL CORPORATION │
│ 24283ca3-2f37-a4c1-45f1-bd87ae9c8087 │ finished │ AMB     │ 162673000      │ General examination of patient │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999942896      │ Dr. Arla414 Fritsch593       │ 2019-06-30 02:35:45 │ 2019-06-30 03:23:10 │ a3d9fbb2-8e79-3105-8bf0-ccd519a97ca2 │ RIVER'S EDGE PRIMARY CARE LLC      │ aad05540-c9cb-3805-b3c4-f9b9d9b42b2e │ RIVER'S EDGE PRIMARY CARE LLC      │
│ 24283ca3-2f37-a4c1-1e3e-fa57d684f9e0 │ finished │ AMB     │ 185349003      │ Encounter for check up         │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999991893      │ Dr. Samuel331 Villalpando154 │ 2019-07-14 02:35:45 │ 2019-07-14 08:32:40 │ 7771ffe2-9f78-3914-ae55-ce0d6a3ccba0 │ BAYSTATE WING HOSPITAL CORPORATION │ 46375470-1e20-3ddc-8dc5-010ba53826b6 │ BAYSTATE WING HOSPITAL CORPORATION │
│ 24283ca3-2f37-a4c1-e614-5624107285b9 │ finished │ AMB     │ 162673000      │ General examination of patient │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999942896      │ Dr. Arla414 Fritsch593       │ 2021-07-04 02:35:45 │ 2021-07-04 03:35:30 │ a3d9fbb2-8e79-3105-8bf0-ccd519a97ca2 │ RIVER'S EDGE PRIMARY CARE LLC      │ aad05540-c9cb-3805-b3c4-f9b9d9b42b2e │ RIVER'S EDGE PRIMARY CARE LLC      │
│ 24283ca3-2f37-a4c1-345f-2edea963a930 │ finished │ AMB     │ 185349003      │ Encounter for check up         │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ PPRF              │ primary performer │ 9999991893      │ Dr. Samuel331 Villalpando154 │ 2021-07-18 02:35:45 │ 2021-07-18 06:16:34 │ 7771ffe2-9f78-3914-ae55-ce0d6a3ccba0 │ BAYSTATE WING HOSPITAL CORPORATION │ 46375470-1e20-3ddc-8dc5-010ba53826b6 │ BAYSTATE WING HOSPITAL CORPORATION │
├──────────────────────────────────────┴──────────┴─────────┴────────────────┴────────────────────────────────┴──────────────────────────────────────┴───────────────────┴───────────────────┴─────────────────┴──────────────────────────────┴─────────────────────┴─────────────────────┴──────────────────────────────────────┴────────────────────────────────────┴──────────────────────────────────────┴────────────────────────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                                              16 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## 4. Condition

In [37]:
con.sql("""
  SELECT
    resource->>'id' AS resource_id,
    resource->'clinicalStatus'->'coding'->0->>'code' AS clinical_status,
    resource->'verificationStatus'->'coding'->0->>'code' AS verification_status,
    resource->'category'->0->'coding'->0->>'code' AS category,
    resource->'code'->'coding'->0->>'code' AS condition_code,
    regexp_replace(resource->'code'->'coding'->0->>'display', ' \((.*?)\)', '') AS condition,
    regexp_extract(resource->'code'->'coding'->0->>'display', '\((.*?)\)', 1) AS condition_type,
    regexp_replace(resource->'subject'->>'reference', 'urn:uuid:', '') AS patient_id,
    regexp_replace(resource->'encounter'->>'reference', 'urn:uuid:', '') AS encounter_id,
    (resource->>'onsetDateTime')::TIMESTAMP AS onset_timestamp,
    (resource->>'recordedDate')::TIMESTAMP AS recorded_timestamp,
  FROM bronze.synthea
  WHERE resource_type='Condition'
  LIMIT 10;
""")

┌──────────────────────────────────────┬─────────────────┬─────────────────────┬─────────────────────┬────────────────┬──────────────────────────────────────────┬────────────────┬──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬─────────────────────┐
│             resource_id              │ clinical_status │ verification_status │      category       │ condition_code │                condition                 │ condition_type │              patient_id              │             encounter_id             │   onset_timestamp   │ recorded_timestamp  │
│               varchar                │     varchar     │       varchar       │       varchar       │    varchar     │                 varchar                  │    varchar     │               varchar                │               varchar                │      timestamp      │      timestamp      │
├──────────────────────────────────────┼─────────────────┼─────────────────────┼─────────────────────┼────────────────┼──────────────────────────────────────────┼────────────────┼──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼─────────────────────┤
│ 24283ca3-2f37-a4c1-8a8b-8bdefe5a3fbb │ active          │ confirmed           │ encounter-diagnosis │ 224295006      │ Only received primary school education   │ finding        │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-84b9-f7ffa9da3120 │ 1993-08-08 03:05:47 │ 1993-08-08 03:05:47 │
│ 24283ca3-2f37-a4c1-a13b-cf32059a0829 │ active          │ confirmed           │ encounter-diagnosis │ 713458007      │ Lack of access to transportation         │ finding        │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-84b9-f7ffa9da3120 │ 1993-08-08 03:05:47 │ 1993-08-08 03:05:47 │
│ 24283ca3-2f37-a4c1-353e-cd7fb09dd3c0 │ active          │ confirmed           │ encounter-diagnosis │ 266934004      │ Transport problem                        │ finding        │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-b6de-137c628f8ba9 │ 2006-06-25 03:26:20 │ 2006-06-25 03:26:20 │
│ 24283ca3-2f37-a4c1-d224-c03feeffe07c │ resolved        │ confirmed           │ encounter-diagnosis │ 314529007      │ Medication review due                    │ situation      │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-c080-c4d2a4544d68 │ 2015-06-21 02:35:45 │ 2015-06-21 02:35:45 │
│ 24283ca3-2f37-a4c1-fcd8-bb9cae1df38c │ resolved        │ confirmed           │ encounter-diagnosis │ 160903007      │ Full-time employment                     │ finding        │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-c080-c4d2a4544d68 │ 2015-06-21 03:28:54 │ 2015-06-21 03:28:54 │
│ 24283ca3-2f37-a4c1-e500-783f39b87b7a │ resolved        │ confirmed           │ encounter-diagnosis │ 423315002      │ Limited social contact                   │ finding        │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-c080-c4d2a4544d68 │ 2015-06-21 03:28:54 │ 2015-06-21 03:28:54 │
│ 24283ca3-2f37-a4c1-3ad0-f484ab6da01c │ resolved        │ confirmed           │ encounter-diagnosis │ 73595000       │ Stress                                   │ finding        │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-2739-f37048c77046 │ 2017-06-25 03:35:21 │ 2017-06-25 03:35:21 │
│ 24283ca3-2f37-a4c1-49e4-e415db041e62 │ resolved        │ confirmed           │ encounter-diagnosis │ 110030002      │ Concussion injury of brain               │ disorder       │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-647f-aae0d05afacd │ 2019-01-12 02:35:45 │ 2019-01-12 02:35:45 │
│ 24283ca3-2f37-a4c1-ae7e-15135aeb69e9 │ resolved        │ confirmed           │ encounter-diagnosis │ 62106007       │ Concussion with no loss of consciousness │ disorder       │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-647f-aae0d05afacd │ 2019-01-12 02:35:45 │ 2019-01-12 02:35:45 │
│ 24283ca3-2f37-a4c1-d70c-bfdc1b0b9325 │ resolved        │ confirmed           │ encounter-diagnosis │ 422650009      │ Social isolation                         │ finding        │ 24283ca3-2f37-a4c1-e740-97f060a230a6 │ 24283ca3-2f37-a4c1-45f1-bd87ae9c8087 │ 2019-06-30 03:23:10 │ 2019-06-30 03:23:10 │
├──────────────────────────────────────┴─────────────────┴─────────────────────┴─────────────────────┴────────────────┴──────────────────────────────────────────┴────────────────┴──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴─────────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                        11 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [10]:
con.close()

In [ ]:
%load_ext watermark
%watermark