# Exploring DuckDB & SQLMesh

Exploring FHIR data infrastructure with DuckDB and SQLMesh

| Date | User | Change Type | Remarks |  
| ---- | ---- | ----------- | ------- |
| 02/03/2026 (SGT)   | Martin | Create   | Notebook created. DuckDB exploration | 
| 17/03/2026 (SGT)   | Martin | Update   | Exploration of post-pipeline tables |

# Content

* [DuckDB](#duckdb)

# DuckDB

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import duckdb
import os
from dotenv import load_dotenv

load_dotenv()

False

## Merging files

For systems that cannot handle docker files, use this to create a single merged DB

In [2]:
base_path = "../data/warehouse"
source_files = os.listdir(base_path)
source_files = [f"{base_path}/{file}" for file in source_files]
print(source_files)
target_db_path = "../data/merged_database.duckdb"

con = duckdb.connect(target_db_path)
con.execute("CREATE SCHEMA IF NOT EXISTS bronze;")

for i, file_path in enumerate(source_files):
  con.execute(f"ATTACH '{file_path}' AS source{i}")

  tables = con.execute(f"SELECT table_name FROM information_schema.tables WHERE table_catalog = 'source{i}'").fetchall()
  print(tables)
  for table_row in tables:
    table_name = table_row[0]
    table_name = f"bronze.{table_name}"

    con.execute(f"CREATE TABLE IF NOT EXISTS {table_name} AS SELECT * FROM source{i}.{table_name} LIMIT 0")
    con.execute(f"INSERT INTO {table_name} SELECT * FROM source{i}.{table_name}")

for i, file_path in enumerate(source_files):
  con.execute(f"DETACH source{i}")

con.close()

print(f"Data from {source_files} has been merged into {target_db_path}")

['../data/warehouse/mimic_fhir.duckdb', '../data/warehouse/mimic_fhir_condition.duckdb', '../data/warehouse/mimic_fhir_disp_org_obs.duckdb', '../data/warehouse/mimic_fhir_encountered.duckdb', '../data/warehouse/mimic_fhir_location.duckdb', '../data/warehouse/mimic_fhir_obs.duckdb', '../data/warehouse/mimic_fhir_patient.duckdb']
[('fhir_resources',)]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[('fhir_resources',)]
[('fhir_resources',)]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[('fhir_resources',)]
[('fhir_resources',)]
[('fhir_resources',)]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[('fhir_resources',)]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Data from ['../data/warehouse/mimic_fhir.duckdb', '../data/warehouse/mimic_fhir_condition.duckdb', '../data/warehouse/mimic_fhir_disp_org_obs.duckdb', '../data/warehouse/mimic_fhir_encountered.duckdb', '../data/warehouse/mimic_fhir_location.duckdb', '../data/warehouse/mimic_fhir_obs.duckdb', '../data/warehouse/mimic_fhir_patient.duckdb'] has been merged into ../data/merged_database.duckdb

In [ ]:
con = duckdb.connect(source_files[1])
tables = con.sql("SHOW TABLES FROM bronze").df()
print(tables)
con.close()

# Exploring Tables

Bronze tables:

- `bronze.fhir_resources`: Collection of raw FHIR resource data
- `bronze.synthea`: Synthea generated data

Silver tables:

- `silver.obs_vital`: Patient vitals recorded in long format

Intermediate tables:

- `intermediate.vitals_wide`: Flattened vitals table containing patient recorded vitals (e.g heart rate, temperature, ...)

Gold (marts) tables:

- `marts.vitals_eda`:

In [11]:
con = duckdb.connect("../data/warehouse/mimic_fhir.duckdb")
dbs = con.sql("SELECT * FROM duckdb_databases").df()
dbs

,database_name,database_oid,path,comment,tags,internal,type,readonly,encrypted,cipher
0,mimic_fhir,685,/Users/martz/Repos/MIMIC-FHIR/notebooks/../dat...,None,{'storage_version': 'v1.0.0+'},False,duckdb,False,False,None

In [12]:
tables = con.sql("SHOW ALL TABLES").df()
tables

,database,schema,name,column_names,column_types,temporary
0,mimic_fhir,bronze,fhir_resources,"[resource_type, resource_id, resource, source_...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR]",False
1,mimic_fhir,bronze,synthea,"[full_url, resource_type, resource, request, s...","[VARCHAR, VARCHAR, JSON, JSON, VARCHAR, VARCHAR]",False
2,mimic_fhir,intermediate,vitals_wide,"[encounter_id, patient_id, effective_datetime,...","[VARCHAR, VARCHAR, TIMESTAMP, DOUBLE, DOUBLE, ...",False
3,mimic_fhir,marts,vitals_eda,"[encounter_id, patient_id, effective_datetime,...","[VARCHAR, VARCHAR, TIMESTAMP, DOUBLE, DOUBLE, ...",False
4,mimic_fhir,silver,obs_vitals,"[resource_id, patient_id, encounter_id, effect...","[VARCHAR, VARCHAR, VARCHAR, TIMESTAMP, VARCHAR...",False
5,mimic_fhir,sqlmesh,_auto_restatements,"[snapshot_name, snapshot_version, next_auto_re...","[VARCHAR, VARCHAR, BIGINT]",False
6,mimic_fhir,sqlmesh,_environment_statements,"[environment_name, plan_id, environment_statem...","[VARCHAR, VARCHAR, VARCHAR]",False
7,mimic_fhir,sqlmesh,_environments,"[name, snapshots, start_at, end_at, plan_id, p...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
8,mimic_fhir,sqlmesh,_intervals,"[id, created_ts, name, identifier, version, st...","[VARCHAR, BIGINT, VARCHAR, VARCHAR, VARCHAR, B...",False
9,mimic_fhir,sqlmesh,_snapshots,"[name, identifier, version, snapshot, kind_nam...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, ...",False
10,mimic_fhir,sqlmesh,_versions,"[schema_version, sqlglot_version, sqlmesh_vers...","[INTEGER, VARCHAR, VARCHAR]",False
11,mimic_fhir,sqlmesh__intermediate,intermediate__vitals_wide__53304136,"[encounter_id, patient_id, effective_datetime,...","[VARCHAR, VARCHAR, TIMESTAMP, DOUBLE, DOUBLE, ...",False
12,mimic_fhir,sqlmesh__marts,marts__vitals_eda__3335598278,"[encounter_id, patient_id, effective_datetime,...","[VARCHAR, VARCHAR, TIMESTAMP, DOUBLE, DOUBLE, ...",False

In [8]:
files = con.sql("SELECT DISTINCT source_file FROM bronze.fhir_resources")
files

┌────────────────────────────────┐
│          source_file           │
│            varchar             │
├────────────────────────────────┤
│ Organization.ndjson            │
│ ObservationED.ndjson           │
│ Location.ndjson                │
│ MedicationDispenseED.ndjson    │
│ ConditionED.ndjson             │
│ ProcedureED.ndjson             │
│ ObservationVitalSignsED.ndjson │
│ EncounterED.ndjson             │
│ Patient.ndjson                 │
└────────────────────────────────┘

In [9]:
con.sql("SELECT * FROM bronze.synthea LIMIT 10")

┌───────────────────────────────────────────────┬──────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────┬────────────────────┬──────────────────────────────────────┐
│                   full_url                    │    resource_type     │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        resource                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         │                    request                     │    source_file     │               file_id                │

## Silver & Gold tables

Exploring Silver and Gold (mart) tables

In [20]:
# silver.obs_vital
con.sql("""
  SELECT *
  FROM silver.obs_vitals
  LIMIT 10
""")

┌──────────────────────────────────────┬──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬────────────┬────────┬────────────────┐
│             resource_id              │              patient_id              │             encounter_id             │ effective_datetime  │ loinc_code │ value  │      unit      │
│               varchar                │               varchar                │               varchar                │      timestamp      │  varchar   │ double │    varchar     │
├──────────────────────────────────────┼──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼────────────┼────────┼────────────────┤
│ e6944724-62ed-53df-b56e-f26d77f8fc14 │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 17:35:00 │ 9279-1     │   18.0 │ breaths/minute │
│ 0df7928c-9982-5ca9-ab43-b965e5ec275f │ 000000ba-735e-5858-a92d-b856d73dd69a │ ab67e413-be5f-5c55-97d2-615c1941d950 │ 2169-09-06 22:55:00 │ 8867-4     │   92.0 │ beats/minute   │
│ 140a6ebd-8e2d-5ae5-9af1-605f430714d3 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 15:42:00 │ 8310-5     │   NULL │ NULL           │
│ fd57fed8-0459-512b-8350-d0b13a51421c │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 19:46:00 │ 2708-6     │   97.0 │ %              │
│ 82ccbb99-eb1a-5261-8ee0-ce5de2d044c8 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 19:46:00 │ 8310-5     │   98.1 │ F              │
│ 5e9ecd5f-4228-54a1-8b17-e163c2464c91 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 21:43:00 │ 9279-1     │   16.0 │ breaths/minute │
│ 77526c5e-4744-549d-b5d0-529b4b806618 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-24 22:02:00 │ 8310-5     │   NULL │ NULL           │
│ 5a0c8b1d-0c24-5515-8297-abb31fd217f2 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-25 02:02:00 │ 2708-6     │   99.0 │ %              │
│ 9823d5c7-09e5-58fe-95f6-bfaa722fdc11 │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-25 02:02:00 │ 8867-4     │   76.0 │ beats/minute   │
│ 3d125d90-6611-5005-8f1d-431e03520ddd │ 000000ba-735e-5858-a92d-b856d73dd69a │ 9142a2a0-fb3e-5aee-96b8-d0fc3fc605f9 │ 2169-10-25 06:31:00 │ 9279-1     │   16.0 │ breaths/minute │
├──────────────────────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴────────────┴────────┴────────────────┤
│ 10 rows                                                                                                                                                               7 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
# intermediate.vitals_wide
con.sql("SELECT * FROM intermediate.vitals_wide LIMIT 10")

┌──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬────────────┬──────────┬──────────┬────────────┬───────────┬───────────┬──────────────┬────────────┬────────────┬──────────────┬─────────────┬─────────────┐
│             encounter_id             │              patient_id              │ effective_datetime  │ temp_value │ hr_value │ rr_value │ spo2_value │ sbp_value │ dbp_value │ temp_present │ hr_present │ rr_present │ spo2_present │ sbp_present │ dbp_present │
│               varchar                │               varchar                │      timestamp      │   double   │  double  │  double  │   double   │  double   │  double   │    int32     │   int32    │   int32    │    int32     │    int32    │    int32    │
├──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼────────────┼──────────┼──────────┼────────────┼───────────┼───────────┼──────────────┼────────────┼────────────┼──────────────┼─────────────┼─────────────┤
│ b8a497c2-7a67-56b0-b078-9b1f3f6c0a06 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2172-05-04 23:36:00 │       NULL │     93.0 │     18.0 │       98.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 75dd8f71-58a4-5a7d-a9da-79f9bc59f139 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2171-10-29 20:47:00 │       99.5 │    111.0 │     20.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ d729a6fb-a212-5996-a5b3-c0fdf348d135 │ fb3949fe-6ae8-575d-b8c2-5d44b414c27c │ 2174-07-27 15:52:00 │       98.1 │     76.0 │     18.0 │       98.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 0fa52380-fe25-5e0e-87aa-5a035dca5233 │ fb48c521-09d6-52d4-99b3-545db8e101b5 │ 2175-05-03 18:41:00 │       NULL │     74.0 │     18.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 413eb62c-13a2-5518-a4a3-4fdca697ef44 │ fb70b4a9-4bba-592c-9c8a-679c9266550d │ 2121-03-01 17:24:00 │       97.5 │     89.0 │     17.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ c594dbe1-635c-5ab4-ad4b-3b38df820f64 │ fb751c9d-0ce3-5371-96bf-dcd0578dae53 │ 2116-08-01 17:54:00 │       97.5 │     92.0 │     18.0 │       97.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 0fae3e9c-d7bb-532d-9b6a-538dc35beb22 │ fb775840-629a-54cb-a30f-1ec55874e9fc │ 2146-05-31 04:50:00 │       97.0 │     78.0 │     19.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ e9fa8536-dbb5-5fde-9c7e-c9e47a90a6d0 │ fb8a8009-ad7b-590c-b1c6-a937e48a7411 │ 2189-06-28 06:51:00 │       97.2 │     62.0 │     18.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 66be00e5-f354-5f6f-b829-360a3296eeba │ fb8aaeb8-08d0-5821-aca4-aa2393893d7e │ 2135-10-19 17:10:00 │       98.2 │     60.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 1a2025ce-b334-5632-9cee-38426bf21d8e │ fb8b131d-2af0-5415-b620-5105acb33ba9 │ 2180-11-01 18:20:00 │       98.6 │     70.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
├──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴────────────┴──────────┴──────────┴────────────┴───────────┴───────────┴──────────────┴────────────┴────────────┴──────────────┴─────────────┴─────────────┤
│ 10 rows                                                                                                                                                                                                                                            15 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [17]:
con.sql("""
  SELECT * 
  FROM intermediate.vitals_wide
  WHERE patient_id='fb348f58-e2e7-5fab-8118-494943e3b84b'
  ORDER BY effective_datetime DESC
  LIMIT 10
""")

┌──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬────────────┬──────────┬──────────┬────────────┬───────────┬───────────┬──────────────┬────────────┬────────────┬──────────────┬─────────────┬─────────────┐
│             encounter_id             │              patient_id              │ effective_datetime  │ temp_value │ hr_value │ rr_value │ spo2_value │ sbp_value │ dbp_value │ temp_present │ hr_present │ rr_present │ spo2_present │ sbp_present │ dbp_present │
│               varchar                │               varchar                │      timestamp      │   double   │  double  │  double  │   double   │  double   │  double   │    int32     │   int32    │   int32    │    int32     │    int32    │    int32    │
├──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼────────────┼──────────┼──────────┼────────────┼───────────┼───────────┼──────────────┼────────────┼────────────┼──────────────┼─────────────┼─────────────┤
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 22:16:00 │       98.4 │     93.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 22:04:00 │       NULL │    110.0 │     NULL │       NULL │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 20:59:00 │       98.4 │    120.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 20:49:00 │       98.2 │     99.0 │     18.0 │       98.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 19:05:00 │       98.1 │     98.0 │     16.0 │       98.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 15:23:00 │       98.2 │    114.0 │     16.0 │       95.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ 165b5824-eaba-5a63-9ec2-ad1699806b0f │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2173-02-17 15:21:00 │       98.2 │    114.0 │     16.0 │       95.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ fcda92e5-4158-52c6-9464-bda0d1ad7dc5 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2172-11-25 07:23:00 │       97.9 │     89.0 │     15.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ fcda92e5-4158-52c6-9464-bda0d1ad7dc5 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2172-11-25 05:38:00 │       98.3 │     94.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
│ fcda92e5-4158-52c6-9464-bda0d1ad7dc5 │ fb348f58-e2e7-5fab-8118-494943e3b84b │ 2172-11-25 02:10:00 │       NULL │     82.0 │     16.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │
├──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴────────────┴──────────┴──────────┴────────────┴───────────┴───────────┴──────────────┴────────────┴────────────┴──────────────┴─────────────┴─────────────┤
│ 10 rows                                                                                                                                                                                                                                            15 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [21]:
# marts.vitals_eda
con.sql("""
  SELECT *
  FROM marts.vitals_eda
  LIMIT 10
""")

┌──────────────────────────────────────┬──────────────────────────────────────┬─────────────────────┬────────────┬──────────┬──────────┬────────────┬───────────┬───────────┬──────────────┬────────────┬────────────┬──────────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬─────────────┬─────────────┬──────────────┬────────────────────────┬───────────┬────────────────────────┬─────────────────┐
│             encounter_id             │              patient_id              │ effective_datetime  │ temp_value │ hr_value │ rr_value │ spo2_value │ sbp_value │ dbp_value │ temp_present │ hr_present │ rr_present │ spo2_present │ sbp_present │ dbp_present │ n_vitals_6 │ n_vitals_5 │ n_vitals_3 │ hour_of_day │ day_of_week │ obs_position │ total_obs_in_encounter │ delta_min │ encounter_duration_hrs │ encounter_phase │
│               varchar                │               varchar                │      timestamp      │   double   │  double  │  double  │   double   │  double   │  double   │    int32     │   int32    │   int32    │    int32     │    int32    │    int32    │   int32    │   int32    │   int32    │    int64    │    int64    │    int64     │         int64          │  double   │         double         │     varchar     │
├──────────────────────────────────────┼──────────────────────────────────────┼─────────────────────┼────────────┼──────────┼──────────┼────────────┼───────────┼───────────┼──────────────┼────────────┼────────────┼──────────────┼─────────────┼─────────────┼────────────┼────────────┼────────────┼─────────────┼─────────────┼──────────────┼────────────────────────┼───────────┼────────────────────────┼─────────────────┤
│ b796d42d-11c4-5a7a-af22-e7e711d6ce9b │ 01593ff8-6440-5ca4-94c5-a622232b8e87 │ 2133-10-11 16:23:00 │       NULL │     82.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          16 │           0 │            3 │                      4 │     147.0 │      7.866666666666666 │ Late            │
│ b796d42d-11c4-5a7a-af22-e7e711d6ce9b │ 01593ff8-6440-5ca4-94c5-a622232b8e87 │ 2133-10-11 21:47:00 │       98.6 │     81.0 │     18.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          21 │           0 │            4 │                      4 │     324.0 │      7.866666666666666 │ Late            │
│ b7989659-0779-5767-aed3-7f3057594a67 │ a5288459-4c42-5ed0-b542-c2a2a857f17d │ 2144-10-23 16:07:00 │       98.7 │    122.0 │     20.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          16 │           5 │            1 │                      4 │      NULL │      6.366666666666666 │ Early           │
│ b7989659-0779-5767-aed3-7f3057594a67 │ a5288459-4c42-5ed0-b542-c2a2a857f17d │ 2144-10-23 16:09:00 │       98.7 │    122.0 │     20.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          16 │           5 │            2 │                      4 │       2.0 │      6.366666666666666 │ Middle          │
│ b7989659-0779-5767-aed3-7f3057594a67 │ a5288459-4c42-5ed0-b542-c2a2a857f17d │ 2144-10-23 20:05:00 │       98.9 │     90.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          20 │           5 │            3 │                      4 │     236.0 │      6.366666666666666 │ Late            │
│ b7989659-0779-5767-aed3-7f3057594a67 │ a5288459-4c42-5ed0-b542-c2a2a857f17d │ 2144-10-23 22:29:00 │       98.8 │     89.0 │     18.0 │      100.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          22 │           5 │            4 │                      4 │     144.0 │      6.366666666666666 │ Late            │
│ b79ca346-7714-51ef-8184-04504641e29b │ 1febffc4-76e6-58f3-8db5-0f7ccaa169ba │ 2168-05-23 21:06:00 │       97.8 │     81.0 │     19.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          21 │           1 │            1 │                      2 │      NULL │     1.7333333333333334 │ Middle          │
│ b79ca346-7714-51ef-8184-04504641e29b │ 1febffc4-76e6-58f3-8db5-0f7ccaa169ba │ 2168-05-23 22:50:00 │       98.0 │     85.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          22 │           1 │            2 │                      2 │     104.0 │     1.7333333333333334 │ Late            │
│ b79de50f-f5eb-54d5-b7c9-744abe34bc45 │ 6f100882-9b00-570e-989e-9ee9e6679862 │ 2135-05-06 15:35:00 │       98.5 │     99.0 │     16.0 │       99.0 │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          15 │           5 │            1 │                      1 │      NULL │                    0.0 │ Late            │
│ b7a2c727-4a0c-5237-8a66-fc5ccee37aee │ a52eadae-df23-53af-b216-79e16233e26c │ 2152-11-20 10:39:00 │       99.7 │    135.0 │     16.0 │       NULL │      NULL │      NULL │            1 │          1 │          1 │            1 │           0 │           0 │          4 │          3 │          1 │          10 │           1 │            1 │                      5 │      NULL │                   4.05 │ Early           │
├──────────────────────────────────────┴──────────────────────────────────────┴─────────────────────┴────────────┴──────────┴──────────┴────────────┴───────────┴───────────┴──────────────┴────────────┴────────────┴──────────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴─────────────┴─────────────┴──────────────┴────────────────────────┴───────────┴────────────────────────┴─────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                              25 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [10]:
con.close()

In [ ]:
%load_ext watermark
%watermark